package view.cmrComercial;
import controller.cmrComercial.CCCliente;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import modelo.cmrComercial.entidad.CECliente;
import util.clases.grlGeneral.CLValidarControles;
import util.clases.grlGeneral.DialogoPadre;
import util.clases.grlGeneral.VerificadorDeTxt;

public class dlgRegistroCliente extends DialogoPadre implements ActionListener {
private CECliente oCECliente;
    private int OperacionAMB=0;
    private CLValidarControles ovalidar;

    /** Creates new form JDHabitacion */
    public dlgRegistroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
       public dlgRegistroCliente(java.awt.Frame parent, boolean modal,CECliente pCECliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ovalidar=new CLValidarControles();
        
      ovalidar.SetListCompnente(new Component[]{TxtApellidoPaterno}, PnlFormulario);
        oCECliente=pCECliente;
        rbtnPersonaNatural.setSelected(true);
        if(pCECliente!=null)
        {
        llenarFormulario();  
        }
        if(RbtnPersonaJuridica.isSelected()) {
            editartextos(false,false);
            LblApellidoPaterno2.setText("Razón Social");
            validarPorPerJuridica();

        }
       TxtNombre.requestFocus();
    }
    public void setABM(int p)
    {
    OperacionAMB=p;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtbgPersona = new javax.swing.ButtonGroup();
        btnGrSexo = new javax.swing.JFileChooser();
        btGrSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PnlFormulario = new javax.swing.JPanel();
        RbtnMaculino = new Opcion.RadioButon();
        DNI3 = new javax.swing.JLabel();
        TxtApellidoMaterno = new javax.swing.JTextField();
        rbtnPersonaNatural = new Opcion.RadioButon();
        TxtCorreoElectronico = new TextField.JTxtNinguno();
        LblCorreoElectronico = new javax.swing.JLabel();
        TxtCelular = new javax.swing.JTextField();
        DNI2 = new javax.swing.JLabel();
        ApellidoMaterno1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblSexo3 = new javax.swing.JLabel();
        RbtnFemenino = new Opcion.RadioButon();
        LblCelular = new javax.swing.JLabel();
        LblNombres1 = new javax.swing.JLabel();
        DNI1 = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        LblTelefono = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        RbtnPersonaJuridica = new Opcion.RadioButon();
        LblRuc = new javax.swing.JLabel();
        TxtRuc = new javax.swing.JTextField();
        TxtDireccion = new TextField.JTxtNinguno();
        jSeparator1 = new javax.swing.JSeparator();
        LblDireccion = new javax.swing.JLabel();
        LblApellidoPaterno2 = new javax.swing.JLabel();
        TxtApellidoPaterno = new TextField.JTxtNinguno();
        btnCancelar1 = new BotonesABM.BtnCancelar();
        BtnGuardar = new BotonesABM.BtnGuardar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Cliente");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12));

        PnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btGrSexo.add(RbtnMaculino);
        RbtnMaculino.setText("Masculino");
        RbtnMaculino.setFont(new java.awt.Font("Verdana", 1, 12));
        RbtnMaculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RbtnMaculinoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RbtnMaculinoKeyReleased(evt);
            }
        });

        DNI3.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI3.setText("Datos Anexos");

        TxtApellidoMaterno.setDocument(new VerificadorDeTxt("String",25,TxtApellidoMaterno));
        TxtApellidoMaterno.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoMaternoKeyPressed(evt);
            }
        });

        BtbgPersona.add(rbtnPersonaNatural);
        rbtnPersonaNatural.setText("Natural");
        rbtnPersonaNatural.setFont(new java.awt.Font("Verdana", 1, 12));
        rbtnPersonaNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPersonaNaturalrbtPersonaNaturalActionPerformed(evt);
            }
        });
        rbtnPersonaNatural.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbtnPersonaNaturalrbtPersonaNaturalKeyReleased(evt);
            }
        });

        TxtCorreoElectronico.setTamanio(100);
        TxtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCorreoElectronicoKeyPressed(evt);
            }
        });

        LblCorreoElectronico.setFont(new java.awt.Font("Verdana", 1, 12));
        LblCorreoElectronico.setText("Correo Electronico:");

        TxtCelular.setDocument(new VerificadorDeTxt("Numero",12,TxtCelular));
        TxtCelular.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCelularActionPerformed(evt);
            }
        });
        TxtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCelularKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCelularKeyReleased(evt);
            }
        });

        DNI2.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI2.setText("Sexo:");

        ApellidoMaterno1.setFont(new java.awt.Font("Verdana", 1, 12));
        ApellidoMaterno1.setText("Apellido Materno:");

        TxtNombre.setDocument(new VerificadorDeTxt("String",25,TxtNombre));
        TxtNombre.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreKeyPressed(evt);
            }
        });

        LblSexo3.setFont(new java.awt.Font("Verdana", 1, 12));
        LblSexo3.setText("Tipo Persona:");

        btGrSexo.add(RbtnFemenino);
        RbtnFemenino.setText("Femenino");
        RbtnFemenino.setFont(new java.awt.Font("Verdana", 1, 12));
        RbtnFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RbtnFemeninoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RbtnFemeninoKeyReleased(evt);
            }
        });

        LblCelular.setFont(new java.awt.Font("Verdana", 1, 12));
        LblCelular.setText("Celular:");

        LblNombres1.setFont(new java.awt.Font("Verdana", 1, 12));
        LblNombres1.setText("Nombres:");

        DNI1.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI1.setText("DNI:");

        TxtDNI.setDocument(new VerificadorDeTxt("Numero",8,TxtDNI));
        TxtDNI.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDNIKeyPressed(evt);
            }
        });

        LblTelefono.setFont(new java.awt.Font("Verdana", 1, 12));
        LblTelefono.setText("Telefono:");

        TxtTelefono.setDocument(new VerificadorDeTxt("Numero",12,TxtTelefono));
        TxtTelefono.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyReleased(evt);
            }
        });

        BtbgPersona.add(RbtnPersonaJuridica);
        RbtnPersonaJuridica.setText("Juridica");
        RbtnPersonaJuridica.setFont(new java.awt.Font("Verdana", 1, 12));
        RbtnPersonaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnPersonaJuridicaRbtnPersonaJuridicaActionPerformed(evt);
            }
        });
        RbtnPersonaJuridica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RbtnPersonaJuridicaRbtnPersonaJuridicaKeyReleased(evt);
            }
        });

        LblRuc.setFont(new java.awt.Font("Verdana", 1, 12));
        LblRuc.setText("RUC:");

        TxtRuc.setDocument(new VerificadorDeTxt("Numero",11,TxtRuc));
        TxtRuc.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRucKeyPressed(evt);
            }
        });

        TxtDireccion.setText("jTxtNinguno1");
        TxtDireccion.setTamanio(200);
        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyPressed(evt);
            }
        });

        LblDireccion.setFont(new java.awt.Font("Verdana", 1, 12));
        LblDireccion.setText("Direccion :");

        LblApellidoPaterno2.setFont(new java.awt.Font("Verdana", 1, 12));
        LblApellidoPaterno2.setText("Apellido Paterno :");

        TxtApellidoPaterno.setTamanio(250);
        TxtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoPaternoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PnlFormularioLayout = new javax.swing.GroupLayout(PnlFormulario);
        PnlFormulario.setLayout(PnlFormularioLayout);
        PnlFormularioLayout.setHorizontalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblApellidoPaterno2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LblNombres1)
                                    .addComponent(ApellidoMaterno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                            .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                            .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                                .addComponent(RbtnMaculino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(RbtnFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addComponent(LblSexo3)
                                .addGap(53, 53, 53)
                                .addComponent(rbtnPersonaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RbtnPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)))
                        .addGap(16, 16, 16))
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNI2)
                            .addComponent(DNI1))
                        .addContainerGap(443, Short.MAX_VALUE))
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addComponent(LblTelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblDireccion)
                                            .addComponent(LblCorreoElectronico))
                                        .addGap(10, 10, 10)
                                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addComponent(TxtRuc, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addComponent(LblRuc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(DNI3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCelular)
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        PnlFormularioLayout.setVerticalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPersonaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtnPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSexo3))
                .addGap(12, 12, 12)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombres1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblApellidoPaterno2)
                    .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoMaterno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI1)
                    .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI2)
                    .addComponent(RbtnMaculino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtnFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DNI3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDireccion)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRuc)
                    .addComponent(TxtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCelular)
                    .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCorreoElectronico))
                .addGap(112, 112, 112))
        );

        jTabbedPane1.addTab("DATOS PERSONALES", PnlFormulario);

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        BtnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnGuardarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BtnGuardarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void validarPorPerJuridica()
    {
        ovalidar.SetListCompnente(new Component[]{TxtApellidoPaterno,TxtRuc,TxtDireccion});
    }
    private void validarPorPerNatural()
    {
        ovalidar.SetListCompnente(new Component[]{TxtApellidoPaterno,TxtApellidoMaterno,TxtNombre,TxtDNI,TxtDireccion});
    }
   private void limpiarCajas()
   {
       TxtApellidoMaterno.setText("");
       TxtNombre.setText("");
       TxtDNI.setText("");
   }
    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed


       eventoGuardar();
      
    }//GEN-LAST:event_BtnGuardarActionPerformed
private void eventoGuardar()
    {
    if(TxtApellidoPaterno.isEditable()){
          ovalidar.validarContorles();
        if(ovalidar.getisVacio()){

            guardar();
            } else{
            JOptionPane.showMessageDialog(null,"Verificar Datos");
            TxtApellidoPaterno.requestFocus();
            }
        }
      else{
            JOptionPane.showMessageDialog(null,"Sellecione un tipo de Persona");
            rbtnPersonaNatural.requestFocus();
            }
}
    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void BtnGuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGuardarKeyReleased
      if(evt.getKeyCode()==evt.VK_UP||evt.getKeyCode()==evt.VK_LEFT||evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_RIGHT) {
          TxtCorreoElectronico.requestFocus();

      }

    }//GEN-LAST:event_BtnGuardarKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       
    }//GEN-LAST:event_formKeyReleased

    private void BtnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGuardarKeyPressed
          if(evt.getKeyCode()==evt.VK_ENTER)
      {
            eventoGuardar();
      }
    }//GEN-LAST:event_BtnGuardarKeyPressed

    private void TxtCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelularKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_TxtCelularKeyReleased

    private void TxtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelularKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtCorreoElectronico.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtTelefono.requestFocus();
        }
}//GEN-LAST:event_TxtCelularKeyPressed

    private void TxtCorreoElectronicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoElectronicoKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            BtnGuardar.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtCelular.requestFocus();
        }
}//GEN-LAST:event_TxtCorreoElectronicoKeyPressed

    private void TxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtRuc.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {

            if(rbtnPersonaNatural.isSelected()){
                RbtnMaculino.requestFocus();}else {
                TxtApellidoPaterno.requestFocus();}

        }
}//GEN-LAST:event_TxtDireccionKeyPressed

    private void TxtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyReleased

}//GEN-LAST:event_TxtTelefonoKeyReleased

    private void TxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtCelular.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtRuc.requestFocus();
        }
}//GEN-LAST:event_TxtTelefonoKeyPressed

    private void TxtRucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRucKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtTelefono.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {

            TxtDireccion.requestFocus();

        }
    }//GEN-LAST:event_TxtRucKeyPressed

    private void RbtnFemeninoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnFemeninoKeyReleased

    }//GEN-LAST:event_RbtnFemeninoKeyReleased

    private void RbtnFemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnFemeninoKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER) {
            RbtnFemenino.setSelected(true);
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT|| evt.getKeyCode()==evt.VK_UP) {
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_LEFT) {
            RbtnMaculino.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtDNI.requestFocus();
        }
}//GEN-LAST:event_RbtnFemeninoKeyPressed

    private void RbtnMaculinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnMaculinoKeyReleased

    }//GEN-LAST:event_RbtnMaculinoKeyReleased

    private void RbtnMaculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnMaculinoKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER) {
            RbtnMaculino.setSelected(true);
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT) {
            RbtnFemenino.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtDNI.requestFocus();
        }
}//GEN-LAST:event_RbtnMaculinoKeyPressed

    private void TxtApellidoMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMaternoKeyPressed

         if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtDNI.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtApellidoPaterno.requestFocus();
        }


}//GEN-LAST:event_TxtApellidoMaternoKeyPressed

    private void TxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyPressed
if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtApellidoPaterno.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            RbtnMaculino.requestFocus();
        }
}//GEN-LAST:event_TxtNombreKeyPressed

    private void TxtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            RbtnMaculino.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtNombre.requestFocus();
        }
}//GEN-LAST:event_TxtDNIKeyPressed

    private void RbtnPersonaJuridicaRbtnPersonaJuridicaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnPersonaJuridicaRbtnPersonaJuridicaKeyReleased
        if(evt.getKeyCode()==evt.VK_ENTER) {
            RbtnPersonaJuridica.setSelected(true);
            editartextos(false,true);
            ovalidar.ReiniciarCajas();
            limpiarCajas();
            validarPorPerJuridica();
            TxtApellidoPaterno.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT|| evt.getKeyCode()==evt.VK_UP) {
            TxtApellidoPaterno.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_LEFT) {
            rbtnPersonaNatural.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtApellidoPaterno.requestFocus();
        }
}//GEN-LAST:event_RbtnPersonaJuridicaRbtnPersonaJuridicaKeyReleased

    private void RbtnPersonaJuridicaRbtnPersonaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnPersonaJuridicaRbtnPersonaJuridicaActionPerformed
        if(RbtnPersonaJuridica.isSelected()) {
            editartextos(false,true);
            LblApellidoPaterno2.setText("Razón Social");
            limpiarCajas();
            ovalidar.ReiniciarCajas();
            validarPorPerJuridica();

        }
}//GEN-LAST:event_RbtnPersonaJuridicaRbtnPersonaJuridicaActionPerformed

    private void rbtnPersonaNaturalrbtPersonaNaturalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnPersonaNaturalrbtPersonaNaturalKeyReleased
        if(evt.getKeyCode()==evt.VK_ENTER) {
            rbtnPersonaNatural.setSelected(true);
            editartextos(true,true);
            ovalidar.ReiniciarCajas();
            validarPorPerNatural();
            TxtApellidoPaterno.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT) {
            RbtnPersonaJuridica.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtApellidoPaterno.requestFocus();
        }
}//GEN-LAST:event_rbtnPersonaNaturalrbtPersonaNaturalKeyReleased

    private void rbtnPersonaNaturalrbtPersonaNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPersonaNaturalrbtPersonaNaturalActionPerformed
        if(rbtnPersonaNatural.isSelected()) {
            editartextos(true,true);
            LblApellidoPaterno2.setText("Apellido Paterno");
            ovalidar.ReiniciarCajas();
            validarPorPerNatural();
        }
}//GEN-LAST:event_rbtnPersonaNaturalrbtPersonaNaturalActionPerformed

    private void TxtApellidoPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoPaternoKeyPressed

        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            if(rbtnPersonaNatural.isSelected()){
                TxtApellidoMaterno.requestFocus();}else {
                TxtDireccion.requestFocus();}
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            rbtnPersonaNatural.requestFocus();
        }

    }//GEN-LAST:event_TxtApellidoPaternoKeyPressed

    private void TxtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCelularActionPerformed
    private void editartextos(boolean pNat,boolean pJur)
    {
        TxtApellidoPaterno.setEditable(pJur);
        TxtApellidoMaterno.setEditable(pNat);
        TxtNombre.setEditable(pNat);
        TxtDNI.setEditable(pNat);
        RbtnMaculino.setEnabled(pNat);
        RbtnFemenino.setEnabled(pNat);
        TxtRuc.setEditable(pJur);
        TxtTelefono.setEditable(pJur);
        TxtCelular.setEditable(pJur);
        TxtDireccion.setEditable(pJur);
        TxtCorreoElectronico.setEditable(pJur);
        
    }
    private void  guardar()
    {
    CECliente oCEClienteAux= new CECliente();
    oCEClienteAux.setApellidoMaterno(TxtApellidoMaterno.getText().trim());
    oCEClienteAux.setCorreo(TxtCorreoElectronico.getText().trim());
    oCEClienteAux.setCodigo("");
    oCEClienteAux.setDNI(TxtDNI.getText().trim());
    oCEClienteAux.setDireccion(TxtDireccion.getText().trim());
    oCEClienteAux.setNombres(TxtNombre.getText().trim());
    oCEClienteAux.setApellidoPaterno((TxtApellidoPaterno.getText().trim()));
    oCEClienteAux.setTelefono(TxtTelefono.getText().trim());
    oCEClienteAux.setRUC(TxtRuc.getText().trim());
    oCEClienteAux.setCelular(TxtCelular.getText());

      if(RbtnFemenino.isSelected())
      {
          oCEClienteAux.setSexo("F");
      }
          else
      {
        if(RbtnMaculino.isSelected())
        {
            oCEClienteAux.setSexo("M");
        }
        
      }
    if(RbtnPersonaJuridica.isSelected())
      {
          oCEClienteAux.setIdTipoPersona(2);
          oCEClienteAux.setSexo(null);
      }
          else
      {
          oCEClienteAux.setIdTipoPersona(1);
      }

    
    oCEClienteAux.setIdSucursal(1);

    ArrayList<CECliente> olista=new ArrayList<CECliente>();
        //Al momento de guardar un dato
       if(OperacionAMB==1)
        { 
           int resul=0;
               olista.add(oCEClienteAux);
                resul=CCCliente.INSCliente(olista);
                if(resul!=0)
                {
                    JOptionPane.showMessageDialog(null,"Operacion Exitosa");                    
                   OperacionAMB=0;
                   dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Operación Fallida");
                }

            
        }
        else
        {  //Al momento de editar
            if(OperacionAMB==2)
            {
                 int resul=0;

                oCEClienteAux.setIdCliente(oCECliente.getIdCliente());
                olista.add(oCEClienteAux);
                resul=CCCliente.UPDCliente(olista);
                  if (resul!=0) {
                      JOptionPane.showMessageDialog(null,"Operacion Exitosa");
                      OperacionAMB=0;
                      dispose();
                    }
                else
                   {
                   JOptionPane.showMessageDialog(null, "No se pudo completar la operación...!");
                   }

            }
        }

    }
    private  void llenarFormulario()
         {
        editartextos(false,false);
        TxtApellidoMaterno.setText(oCECliente.getApellidoMaterno());
        TxtDireccion.setText(oCECliente.getDireccion());
        TxtRuc.setText(oCECliente.getRUC());
        TxtNombre.setText(oCECliente.getNombres());
        TxtApellidoPaterno.setText(oCECliente.getApellidoPaterno());
        TxtTelefono.setText(oCECliente.getTelefono());
        TxtDNI.setText(oCECliente.getDNI());
        TxtCorreoElectronico.setText(oCECliente.getCorreo());
        TxtCelular.setText(oCECliente.getCelular());
        if(oCECliente.getSexo()!=null){
        if(oCECliente.getSexo().equals("M"))
            {

            RbtnMaculino.setSelected(true);
            }
        else
            {
            RbtnFemenino.setSelected(true);
            }
             }
        if(oCECliente.getIdTipoPersona()==1)
            {

            rbtnPersonaNatural.setSelected(true);
            editartextos(true,true);
            }
        else
            {
            
            RbtnPersonaJuridica.setSelected(true);
            editartextos(false,true);
            }

         
    }                     
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaterno1;
    private javax.swing.ButtonGroup BtbgPersona;
    private BotonesABM.BtnGuardar BtnGuardar;
    private javax.swing.JLabel DNI1;
    private javax.swing.JLabel DNI2;
    private javax.swing.JLabel DNI3;
    private javax.swing.JLabel LblApellidoPaterno2;
    private javax.swing.JLabel LblCelular;
    private javax.swing.JLabel LblCorreoElectronico;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblNombres1;
    private javax.swing.JLabel LblRuc;
    private javax.swing.JLabel LblSexo3;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JPanel PnlFormulario;
    private Opcion.RadioButon RbtnFemenino;
    private Opcion.RadioButon RbtnMaculino;
    private Opcion.RadioButon RbtnPersonaJuridica;
    private javax.swing.JTextField TxtApellidoMaterno;
    private TextField.JTxtNinguno TxtApellidoPaterno;
    private javax.swing.JTextField TxtCelular;
    private TextField.JTxtNinguno TxtCorreoElectronico;
    private javax.swing.JTextField TxtDNI;
    private TextField.JTxtNinguno TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRuc;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.ButtonGroup btGrSexo;
    private BotonesABM.BtnCancelar btnCancelar1;
    private javax.swing.JFileChooser btnGrSexo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Opcion.RadioButon rbtnPersonaNatural;
    // End of variables declaration//GEN-END:variables

    private static final String ACTION_CLOSE = "ACTION_CLOSE";
    private static final String ACTION_GUARDAR = "ACTION_NUEVO";
    protected JRootPane createRootPane()
    {
        JRootPane rootPane = new JRootPane();

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        KeyStroke nuevo = KeyStroke.getKeyStroke(KeyEvent.VK_G,java.awt.event.InputEvent.CTRL_DOWN_MASK );
        rootPane.registerKeyboardAction(this,ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        rootPane.registerKeyboardAction(this,ACTION_GUARDAR, nuevo, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
    public void actionPerformed(ActionEvent e)
    {
        if(e.getActionCommand().equals(ACTION_CLOSE))
        {
            dispose();
        }
 else{
         if(e.getActionCommand().equals(ACTION_GUARDAR))
        {
            eventoGuardar();
        }
    }
    }
}
