use dbaynv1;
truncate vtat06_pedido_detalle;
TRUNCATE vtat15_pedido_estado;
TRUNCATE vtat18_nota_credito_detalle;
TRUNCATE vtat25_nota_credito_estado;
TRUNCATE vtat17_nota_credito;
TRUNCATE vtat27_comprobante_devolucion_detalle;
TRUNCATE vtat28_comprobante_devolucion_estado;
TRUNCATE vtat26_comprobante_devolucion;
TRUNCATE vtat09_comprobante_venta_detalle;
TRUNCATE vtat20_ingreso_financiero_detalle;
TRUNCATE vtat19_ingreso_financiero;
TRUNCATE vtat08_comprobante_venta;
TRUNCATE tsot07_cuadre_caja_tipo_pago;
TRUNCATE tsot02_cuadre_caja_detalle;
TRUNCATE tsot01_cuadre_caja;
truncate  almt14_transferencia_almacen;
truncate  almt29_ingreso_nota_credito;
truncate  almt30_ingreso_comprobante_devolucion;
truncate cmpt02_orden_compra_detalle;
truncate cmpt03_orden_compra_estado;
truncate cmpt05_comprobante_compra_detalle;
truncate cmpt06_comprobante_compra_estado;
truncate cmpt12_egreso_financiero;
truncate cmpt13_egreso_financiero_detalle;
truncate ctbt07_forma_pago;
truncate ctbt08_forma_pago_detalle;
truncate vtat14_comprobante_venta_estado;
truncate almt18_ingreso_producto;
truncate almt34_guia_remision_recibido ;
truncate ctbt02_cuenta_corriente;
truncate ctbt10_cuenta_corriente_proveedor;

truncate almt22_transferencia_ingreso;
truncate almt27_ingreso_producto_estado;
truncate almt36_guia_remision_recibido_estado;
truncate cmpt01_orden_compra;
truncate cmpt04_comprobante_compra;
truncate ctbt03_movimiento_cuenta;
truncate ctbt11_movimiento_cuenta_proveedor;

truncate almt25_salida_pedido;
truncate almt20_salida_producto;
truncate  vtat05_pedido;

truncate  almt24_ingreso_compra;
truncate almt26_transferencia_salida;
truncate almt28_salida_producto_estado;
truncate almt19_ingreso_producto_detalle;
truncate almt21_salida_producto_detalle;
truncate almt35_guia_remision_recibido_detalle ;
truncate vtat31_proforma_detalle;
truncate almt23_transferencia_almacen_detalle;
UPDATE grlt02_correlativo set valor=0 WHERE IdCorrelativo=6 OR IdCorrelativo=7 OR IdCorrelativo=8;