/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgconfBackup.java
 *
 * Created on 07-may-2012, 12:00:47
 */

package view.grlGeneral;

import controller.acceso.ConexionBD;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.clases.grlGeneral.DialogoPadre;
import view.FrmSistemaMenu;

/**
 *
 * @author Morales
 */
public class DlgconfBackup extends DialogoPadre {

    /** Creates new form DlgconfBackup */
    public DlgconfBackup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        URL url = getClass().getResource("/controller/acceso/PropiedadesDeConfiguracion.properties");

File f = new File( url.getFile().replace("%20", " "));
	        //Crear el objeto properties

        Properties props = new Properties();
                try {
            //    props.load(new FileInputStream(f));
                    InputStream oinp=ConexionBD.class.getResourceAsStream("PropiedadesDeConfiguracion.properties");
                props.load(oinp);
                System.out.println(oinp.toString());

            } catch (IOException ex) {
                Logger.getLogger(FrmSistemaMenu.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex);
            }
        String dir=props.getProperty("conf.dir_backup");
        txtDir.setText(dir);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        txtDir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar1 = new BotonesABM.BtnGuardar();
        btnCancelar1 = new BotonesABM.BtnCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtDir.setEditable(false);

        jLabel1.setText("Dir. Exe:");

        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDir, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int returnVal = jFileChooser1.showSaveDialog(this);
    if (returnVal == jFileChooser1.APPROVE_OPTION) {
        File ofile = jFileChooser1.getSelectedFile();
        txtDir.setText(ofile.getPath());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed

        dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed


 URL url = this.getClass().getResource("/controller/acceso/PropiedadesDeConfiguracion.properties");
File f = new File( url.getFile().replace("%20", " "));

	        //Crear el objeto properties
	        Properties properties = new Properties();

	        try {
	            // Cargar las propiedades del archivo
	          //  properties.load(new FileInputStream(archivo));

//                    try {
//
//
//                        // properties.load(ConexionBD.class.getResourceAsStream("PropiedadesDeConfiguracion.properties"));
//                    } catch (IOException ex) {
//                        Logger.getLogger(FrmSistemaMenu.class.getName()).log(Level.SEVERE, null, ex);
//                    }
                    properties.load(new FileInputStream(f));
	            properties.setProperty("conf.dir_backup",txtDir.getText());
	            // Escribier en el archivo los cambios
	                   //     FileOutputStream fos=new FileOutputStream(archivo.toString().replace("\\", "/"));
                    
                    
                    properties.store( new FileOutputStream(f),null);
                   // properties.store( new FileOutputStream(archivo.toString().replace("\\", "/")), "sistema");
	                        
                                

	                } catch (FileNotFoundException e) {
	            System.out.println(e.getMessage());
	        } catch (IOException e) {
	            System.out.println(e.getMessage());
	        }






        

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonesABM.BtnCancelar btnCancelar1;
    private BotonesABM.BtnGuardar btnGuardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDir;
    // End of variables declaration//GEN-END:variables

}
