/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 17-mar-2012, 17:18:37
 */

package view.grlGeneral;

import controller.vtaVenta.CCTipoComprobante;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import modelo.grlGeneral.datos.CDImprimir;
import modelo.vtaVenta.entidad.CETipoComprobante;
import util.clases.almAlmacen.JTableX;
import util.clases.grlGeneral.CLComboBox;
import util.clases.grlGeneral.CLImprimir;
import util.clases.grlGeneral.CLPanelImpresion;
import util.clases.grlGeneral.CLRedondear;
import util.clases.grlGeneral.DialogoPadre;
import view.FrmSistemaMenu;

/**
 *
 * @author Morales
 */
public class dlgImprimir extends DialogoPadre {

    /** Creates new form NewJDialog */

    List<CLImprimir> list=null;
    public dlgImprimir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TblImprimir.setSurrendersFocusOnKeystroke(true);
        TblImprimir.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        ((JTableX)TblImprimir).setSelectAllForEdit(true);
         listar(1);
        CbxTipoComprobante.setModel(CLComboBox.cargarCombo(CCTipoComprobante.listaAll()));
        dibujar();
    }

     private void dibujar()
    {
         PnlGrafica.removeAll();
        PnlGrafica.repaint();
         CLPanelImpresion  quadPanel = new CLPanelImpresion(); // Crea el Panel
                        quadPanel.SetLstImprimir(list,((CETipoComprobante )CbxTipoComprobante.getSelectedItem()).getIdTipoComprobante());
                        quadPanel.setBackground(Color.white); //Color del Panel
                        quadPanel.setBounds(0, 0, PnlGrafica.getWidth(), PnlGrafica.getHeight());
                       // quadPanel.setBounds(0, 0,400,400);

        PnlGrafica.add(quadPanel);
    }
    private void listar(int idcom)
    {
        list=CDImprimir.Listado(idcom);
        limpiarTabla();
        for (CLImprimir oCEAlmacenProductoTemp : list)
                {
                    Vector oVector=new Vector();
                        oVector.add(oCEAlmacenProductoTemp.getIdImprimir());
                        oVector.add(oCEAlmacenProductoTemp.getDescripcion());
                        oVector.add(oCEAlmacenProductoTemp.getX());
                        oVector.add(oCEAlmacenProductoTemp.getY());
                        double xcm=(2.54/72)*(oCEAlmacenProductoTemp.getX());
                        double ycm=(2.54/72)*(oCEAlmacenProductoTemp.getY());
                        oVector.add(CLRedondear.RedondearDouble(xcm,2));
                        oVector.add(CLRedondear.RedondearDouble(ycm,2));
                        ((DefaultTableModel)TblImprimir.getModel()).addRow(oVector);

                }

    }

    public void limpiarTabla()
    {
        int filas=TblImprimir.getRowCount();

        if(filas>0)
            for(int i=0;i<filas;i++)
            {
               ((DefaultTableModel)TblImprimir.getModel()).removeRow(0);
            }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblImprimir = new util.clases.almAlmacen.JTableX();
        btnGuardar1 = new BotonesABM.BtnGuardar();
        CbxTipoComprobante = new ComboBox.ComboBox();
        label1 = new Label.Label();
        PnlGrafica = new javax.swing.JPanel();
        btnCancelar1 = new BotonesABM.BtnCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblImprimir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descripcion", "Xpx", "Ypx", "Xcm", "Ycm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblImprimir.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TblImprimir.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TblImprimir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TblImprimirKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TblImprimir);
        TblImprimir.getColumnModel().getColumn(0).setPreferredWidth(20);
        TblImprimir.getColumnModel().getColumn(1).setPreferredWidth(120);
        TblImprimir.getColumnModel().getColumn(2).setMinWidth(0);
        TblImprimir.getColumnModel().getColumn(2).setPreferredWidth(0);
        TblImprimir.getColumnModel().getColumn(2).setMaxWidth(0);
        TblImprimir.getColumnModel().getColumn(3).setMinWidth(0);
        TblImprimir.getColumnModel().getColumn(3).setPreferredWidth(0);
        TblImprimir.getColumnModel().getColumn(3).setMaxWidth(0);
        TblImprimir.getColumnModel().getColumn(4).setPreferredWidth(45);
        TblImprimir.getColumnModel().getColumn(5).setPreferredWidth(45);

        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        CbxTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTipoComprobanteActionPerformed(evt);
            }
        });

        label1.setText("Comprob :");

        javax.swing.GroupLayout PnlGraficaLayout = new javax.swing.GroupLayout(PnlGrafica);
        PnlGrafica.setLayout(PnlGraficaLayout);
        PnlGraficaLayout.setHorizontalGroup(
            PnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        PnlGraficaLayout.setVerticalGroup(
            PnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(907, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnlGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed


        List<CLImprimir> lista= new ArrayList<CLImprimir>();
    CLImprimir oCLImprimir;
        for( int i =0;i<TblImprimir.getRowCount();i++)
            {
                double xcm=(72/2.54)*(Double.parseDouble(TblImprimir.getValueAt(i, 4).toString()));
                double ycm=(72/2.54)*(Double.parseDouble(TblImprimir.getValueAt(i, 5).toString()));
                TblImprimir.setValueAt((int)CLRedondear.RedondearDouble(xcm, 0), i, 2);
                TblImprimir.setValueAt((int)CLRedondear.RedondearDouble(ycm, 0), i, 3);
                oCLImprimir= new CLImprimir();
                
                if(TblImprimir.getValueAt(i, 0)!=null){
                    oCLImprimir.setIdImprimir(Integer.parseInt(TblImprimir.getValueAt(i,0).toString()));
                    }
                if(TblImprimir.getValueAt(i, 2)!=null){
                    oCLImprimir.setX(Integer.parseInt(TblImprimir.getValueAt(i, 2).toString()));
                    }
                if(TblImprimir.getValueAt(i, 3)!=null){
                    oCLImprimir.setY(Integer.parseInt(TblImprimir.getValueAt(i,3).toString()));
                    }
                lista.add(oCLImprimir);
        
                
        }

                  if(CDImprimir.Actualizar(lista))
                  {
                    listar(((CETipoComprobante )CbxTipoComprobante.getSelectedItem()).getIdTipoComprobante());
                    dibujar();
                    FrmSistemaMenu.setListImprimir(CDImprimir.Listado(0));
                    PnlGrafica.repaint();
                    if(TblImprimir.getRowCount()>0){
                    TblImprimir.requestFocus();
                    TblImprimir.changeSelection(0, 2, false, false);
                  }
                    else
                  {
                    JOptionPane.showMessageDialog(this, "Operaccion Fallida" );
                  }

        }

                
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void CbxTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTipoComprobanteActionPerformed


        listar(((CETipoComprobante )CbxTipoComprobante.getSelectedItem()).getIdTipoComprobante());
        dibujar();
        repaint();
    }//GEN-LAST:event_CbxTipoComprobanteActionPerformed

    private void TblImprimirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblImprimirKeyPressed

        if(TblImprimir.getRowCount()>0){
       TblImprimir.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"ProjSave");
        TblImprimir.getActionMap().put("ProjSave", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                 btnGuardar1.requestFocus();
            }
        });
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TblImprimirKeyPressed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed

       dispose();

    }//GEN-LAST:event_btnCancelar1ActionPerformed

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox.ComboBox CbxTipoComprobante;
    private javax.swing.JPanel PnlGrafica;
    private javax.swing.JTable TblImprimir;
    private BotonesABM.BtnCancelar btnCancelar1;
    private BotonesABM.BtnGuardar btnGuardar1;
    private javax.swing.JScrollPane jScrollPane1;
    private Label.Label label1;
    // End of variables declaration//GEN-END:variables

}
