package view.cmrComercial;
import controller.cmrComercial.CCEmpleado;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import modelo.cmrComercial.entidad.CEEmpleado;
import util.clases.grlGeneral.CLValidarControles;
import util.clases.grlGeneral.DialogoPadre;
import util.clases.grlGeneral.VerificadorDeTxt;

public class dlgRegistroEmpleado extends DialogoPadre implements ActionListener{
private CEEmpleado oCEEmpleado;
    private int OperacionAMB=0;
    private CLValidarControles ovalidar;

    /** Creates new form JDHabitacion */
    public dlgRegistroEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
       public dlgRegistroEmpleado(java.awt.Frame parent, boolean modal,CEEmpleado pCEEmpleado,int TipoEmpleado) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ovalidar=new CLValidarControles();
        
      ovalidar.SetListCompnente(new Component[]{TxtApellidoPaterno,TxtDNI}, PnlFormulario);
        oCEEmpleado=pCEEmpleado;
        if(pCEEmpleado!=null)
        {
        llenarFormulario();  
        }
             editartextos(true,true);
        
        TxtNombre.requestFocus();
      
    }
    public void setABM(int p)
    {
    OperacionAMB=p;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtbgPersona = new javax.swing.ButtonGroup();
        btnGrSexo = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PnlFormulario = new javax.swing.JPanel();
        LblApellidoPaterno2 = new javax.swing.JLabel();
        TxtApellidoPaterno = new javax.swing.JTextField();
        ApellidoMaterno1 = new javax.swing.JLabel();
        LblNombres1 = new javax.swing.JLabel();
        DNI1 = new javax.swing.JLabel();
        DNI2 = new javax.swing.JLabel();
        DNI3 = new javax.swing.JLabel();
        LblDireccion = new javax.swing.JLabel();
        LblTelefono = new javax.swing.JLabel();
        LblCelular = new javax.swing.JLabel();
        LblCorreoElectronico = new javax.swing.JLabel();
        TxtCorreoElectronico = new TextField.JTxtNinguno();
        TxtCelular = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtDireccion = new TextField.JTxtNinguno();
        RbtnMaculino = new Opcion.RadioButon();
        RbtnFemenino = new Opcion.RadioButon();
        TxtNombre = new javax.swing.JTextField();
        TxtApellidoMaterno = new javax.swing.JTextField();
        TxtDNI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar1 = new BotonesABM.BtnCancelar();
        BtnGuardar = new BotonesABM.BtnGuardar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12));

        PnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LblApellidoPaterno2.setFont(new java.awt.Font("Verdana", 1, 12));
        LblApellidoPaterno2.setText("Apellido Paterno :");

        TxtApellidoPaterno.setDocument(new VerificadorDeTxt("String",25,TxtApellidoPaterno));
        TxtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoPaternoKeyPressed(evt);
            }
        });

        ApellidoMaterno1.setFont(new java.awt.Font("Verdana", 1, 12));
        ApellidoMaterno1.setText("Apellido Materno:");

        LblNombres1.setFont(new java.awt.Font("Verdana", 1, 12));
        LblNombres1.setText("Nombres:");

        DNI1.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI1.setText("DNI:");

        DNI2.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI2.setText("Sexo:");

        DNI3.setFont(new java.awt.Font("Verdana", 1, 12));
        DNI3.setText("Datos Anexos");

        LblDireccion.setFont(new java.awt.Font("Verdana", 1, 12));
        LblDireccion.setText("Direccion:");

        LblTelefono.setFont(new java.awt.Font("Verdana", 1, 12));
        LblTelefono.setText("Telefono:");

        LblCelular.setFont(new java.awt.Font("Verdana", 1, 12));
        LblCelular.setText("Celular:");

        LblCorreoElectronico.setFont(new java.awt.Font("Verdana", 1, 12));
        LblCorreoElectronico.setText("Correo Electronico:");

        TxtCorreoElectronico.setText("jTxtNinguno1");
        TxtCorreoElectronico.setTamanio(100);
        TxtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCorreoElectronicoKeyPressed(evt);
            }
        });

        TxtCelular.setDocument(new VerificadorDeTxt("Numero",12,TxtCelular));
        TxtCelular.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCelularKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCelularKeyReleased(evt);
            }
        });

        TxtTelefono.setDocument(new VerificadorDeTxt("Numero",12,TxtTelefono));
        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyReleased(evt);
            }
        });

        TxtDireccion.setTamanio(100);
        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyPressed(evt);
            }
        });

        buttonGroup1.add(RbtnMaculino);
        RbtnMaculino.setText("Masculino");
        RbtnMaculino.setFont(new java.awt.Font("Verdana", 1, 12));
        RbtnMaculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RbtnMaculinoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RbtnMaculinoKeyReleased(evt);
            }
        });

        buttonGroup1.add(RbtnFemenino);
        RbtnFemenino.setText("Femenino");
        RbtnFemenino.setFont(new java.awt.Font("Verdana", 1, 12));
        RbtnFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RbtnFemeninoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RbtnFemeninoKeyReleased(evt);
            }
        });

        TxtNombre.setDocument(new VerificadorDeTxt("String",25,TxtNombre));
        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreKeyPressed(evt);
            }
        });

        TxtApellidoMaterno.setDocument(new VerificadorDeTxt("String",25,TxtApellidoMaterno));
        TxtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtApellidoMaternoKeyPressed(evt);
            }
        });

        TxtDNI.setDocument(new VerificadorDeTxt("Numero",8,TxtDNI));
        TxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDNIKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PnlFormularioLayout = new javax.swing.GroupLayout(PnlFormulario);
        PnlFormulario.setLayout(PnlFormularioLayout);
        PnlFormularioLayout.setHorizontalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addComponent(DNI1)
                                .addGap(113, 113, 113)
                                .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(DNI3))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DNI2)
                                    .addComponent(LblTelefono)
                                    .addComponent(LblDireccion))
                                .addGap(77, 77, 77)
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addComponent(RbtnMaculino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RbtnFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCelular)
                                    .addComponent(LblCorreoElectronico))
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ApellidoMaterno1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(LblApellidoPaterno2))
                                .addGap(26, 26, 26)
                                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlFormularioLayout.createSequentialGroup()
                                .addComponent(LblNombres1)
                                .addGap(80, 80, 80)
                                .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                        .addGap(129, 129, 129))))
        );
        PnlFormularioLayout.setVerticalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombres1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblApellidoPaterno2)
                    .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoMaterno1)
                    .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI1))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI2)
                    .addComponent(RbtnMaculino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtnFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(DNI3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblDireccion))
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblCelular)
                    .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCorreoElectronico)
                    .addComponent(TxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DATOS PERSONALES", PnlFormulario);

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        BtnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnGuardarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BtnGuardarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void RbtnMaculinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnMaculinoKeyReleased


    }//GEN-LAST:event_RbtnMaculinoKeyReleased

    private void RbtnFemeninoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnFemeninoKeyReleased

        
    }//GEN-LAST:event_RbtnFemeninoKeyReleased

    private void TxtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyReleased

    }//GEN-LAST:event_TxtTelefonoKeyReleased

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed


  eventoGuardar();
        

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void eventoGuardar()
    {

          ovalidar.validarContorles();
        if(ovalidar.getisVacio()){

            guardar();
            } else{
            JOptionPane.showMessageDialog(null,"Verificar Datos");
            TxtApellidoPaterno.requestFocus();
            }
    }
    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void BtnGuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGuardarKeyReleased
      if(evt.getKeyCode()==evt.VK_UP||evt.getKeyCode()==evt.VK_LEFT||evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_RIGHT) {
          TxtCorreoElectronico.requestFocus();
      }
    
    }//GEN-LAST:event_BtnGuardarKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
       
    }//GEN-LAST:event_formKeyReleased

    private void TxtApellidoPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoPaternoKeyPressed
         if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
             TxtApellidoMaterno.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
           TxtNombre.requestFocus();
        }
      
    }//GEN-LAST:event_TxtApellidoPaternoKeyPressed

    private void TxtApellidoMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMaternoKeyPressed
          if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtDNI.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtApellidoPaterno.requestFocus();
        }
    }//GEN-LAST:event_TxtApellidoMaternoKeyPressed

    private void TxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyPressed
       if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
             TxtApellidoMaterno.requestFocus();
        }
       
    }//GEN-LAST:event_TxtNombreKeyPressed

    private void TxtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyPressed
          if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            RbtnMaculino.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtNombre.requestFocus();
        }
    }//GEN-LAST:event_TxtDNIKeyPressed

    private void RbtnMaculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnMaculinoKeyPressed
           if(evt.getKeyCode()==evt.VK_ENTER) {
            RbtnMaculino.setSelected(true);
          TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT) {
            RbtnFemenino.requestFocus();
        }
       if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtDNI.requestFocus();
        }
    }//GEN-LAST:event_RbtnMaculinoKeyPressed

    private void RbtnFemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RbtnFemeninoKeyPressed
            if(evt.getKeyCode()==evt.VK_ENTER) {
            RbtnFemenino.setSelected(true);
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_RIGHT|| evt.getKeyCode()==evt.VK_UP) {
           TxtDireccion.requestFocus();
        }
     if(evt.getKeyCode()==evt.VK_LEFT) {
           RbtnMaculino.requestFocus();
        }
     if(evt.getKeyCode()==evt.VK_DOWN) {
            TxtDireccion.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtDNI.requestFocus();
        }
    }//GEN-LAST:event_RbtnFemeninoKeyPressed

    private void TxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtCelular.requestFocus();
        }
     if(evt.getKeyCode()==evt.VK_UP) {
            TxtDireccion.requestFocus();
        }
    }//GEN-LAST:event_TxtTelefonoKeyPressed

    private void BtnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnGuardarKeyPressed
          if(evt.getKeyCode()==evt.VK_ENTER)
      {
            eventoGuardar();
      }
    }//GEN-LAST:event_BtnGuardarKeyPressed

    private void TxtCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelularKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtCorreoElectronico.requestFocus();
        }
     if(evt.getKeyCode()==evt.VK_UP) {
            TxtTelefono.requestFocus();
        }
}//GEN-LAST:event_TxtCelularKeyPressed

    private void TxtCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelularKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_TxtCelularKeyReleased

    private void TxtCorreoElectronicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoElectronicoKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            BtnGuardar.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtCelular.requestFocus();
        }
}//GEN-LAST:event_TxtCorreoElectronicoKeyPressed

    private void TxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionKeyPressed
    private void editartextos(boolean pNat,boolean pJur)
    {
        TxtApellidoPaterno.setEditable(pJur);
        TxtApellidoMaterno.setEditable(pNat);
        TxtNombre.setEditable(pNat);
        TxtDNI.setEditable(pNat);
        RbtnMaculino.setEnabled(pNat);
        RbtnFemenino.setEnabled(pNat);
        TxtTelefono.setEditable(pJur);
        TxtCelular.setEditable(pJur);
        TxtDireccion.setEditable(pJur);
        TxtCorreoElectronico.setEditable(pJur);
        
    }
    private void  guardar()
    {
    CEEmpleado oCEEmpleadoAux= new CEEmpleado();
    oCEEmpleadoAux.setApellidoMaterno(TxtApellidoMaterno.getText());
    oCEEmpleadoAux.setCorreo(TxtCorreoElectronico.getText());
    oCEEmpleadoAux.setCodigo("");
    oCEEmpleadoAux.setDNI(TxtDNI.getText());
    oCEEmpleadoAux.setDireccion(TxtDireccion.getText());
    oCEEmpleadoAux.setNombres(TxtNombre.getText());
    oCEEmpleadoAux.setApellidoPaterno((TxtApellidoPaterno.getText()));
    oCEEmpleadoAux.setTelefono(TxtTelefono.getText());
    oCEEmpleadoAux.setCelular(TxtCelular.getText());
      if(RbtnFemenino.isSelected())
      {
          oCEEmpleadoAux.setSexo("F");
      }
          else
      {
          oCEEmpleadoAux.setSexo("M");
      }
    
       
      

    
    oCEEmpleadoAux.setIdSucursal(1);

    ArrayList<CEEmpleado> olista=new ArrayList<CEEmpleado>();
        //Al momento de guardar un dato
       if(OperacionAMB==1)
        { 
               olista.add(oCEEmpleadoAux);
               int resul=CCEmpleado.INSEmpleado(olista);
                if(resul!=0)
                {
                    JOptionPane.showMessageDialog(null,"Operacion Exitosa");                    
                   OperacionAMB=0;
                   dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Operación Fallida");
                }

            
        }
        else
        {  //Al momento de editar
            if(OperacionAMB==2)
            {
                int resul=JOptionPane.showConfirmDialog(this, "¿Esta seguro de modificar? ", "Dialogo de Confirmación", JOptionPane.YES_NO_OPTION);
                if (resul==JOptionPane.YES_OPTION) {
                oCEEmpleadoAux.setIdEmpleado(oCEEmpleado.getIdEmpleado());
                olista.add(oCEEmpleadoAux);
                resul=CCEmpleado.UPDEmpleado(olista);
                  if (resul!=0) {
                      JOptionPane.showMessageDialog(null,"Operacion Exitosa");
                      OperacionAMB=0;
                      dispose();
                    }
                else
                   {
                   JOptionPane.showMessageDialog(null, "No se pudo completar la operación...!");
                   }


                }

            }
        }

    }
    private  void llenarFormulario()
         {
       
        TxtApellidoMaterno.setText(oCEEmpleado.getApellidoMaterno());
        TxtNombre.setText(oCEEmpleado.getNombres());
        TxtApellidoPaterno.setText(oCEEmpleado.getApellidoPaterno());
        TxtTelefono.setText(oCEEmpleado.getTelefono());
        TxtDNI.setText(oCEEmpleado.getDNI());
        TxtCorreoElectronico.setText(oCEEmpleado.getCorreo());
        TxtCelular.setText(oCEEmpleado.getCelular());
        TxtDireccion.setText(oCEEmpleado.getDireccion());
        if(oCEEmpleado.getSexo().equals("M"))
            {

            RbtnMaculino.setSelected(true);
            }
        else
            {
            RbtnFemenino.setSelected(true);
            }


    }                     
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaterno1;
    private javax.swing.ButtonGroup BtbgPersona;
    private BotonesABM.BtnGuardar BtnGuardar;
    private javax.swing.JLabel DNI1;
    private javax.swing.JLabel DNI2;
    private javax.swing.JLabel DNI3;
    private javax.swing.JLabel LblApellidoPaterno2;
    private javax.swing.JLabel LblCelular;
    private javax.swing.JLabel LblCorreoElectronico;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblNombres1;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JPanel PnlFormulario;
    private Opcion.RadioButon RbtnFemenino;
    private Opcion.RadioButon RbtnMaculino;
    private javax.swing.JTextField TxtApellidoMaterno;
    private javax.swing.JTextField TxtApellidoPaterno;
    private javax.swing.JTextField TxtCelular;
    private TextField.JTxtNinguno TxtCorreoElectronico;
    private javax.swing.JTextField TxtDNI;
    private TextField.JTxtNinguno TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private BotonesABM.BtnCancelar btnCancelar1;
    private javax.swing.JFileChooser btnGrSexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private static final String ACTION_CLOSE = "ACTION_CLOSE";
    private static final String ACTION_GUARDAR = "ACTION_NUEVO";
    protected JRootPane createRootPane()
    {
        JRootPane rootPane = new JRootPane();

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        KeyStroke nuevo = KeyStroke.getKeyStroke(KeyEvent.VK_G,java.awt.event.InputEvent.CTRL_DOWN_MASK );
        rootPane.registerKeyboardAction(this,ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        rootPane.registerKeyboardAction(this,ACTION_GUARDAR, nuevo, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
    public void actionPerformed(ActionEvent e)
    {
        if(e.getActionCommand().equals(ACTION_CLOSE))
        {
            dispose();
        }
 else{
         if(e.getActionCommand().equals(ACTION_GUARDAR))
        {
            eventoGuardar();
        }
    }
    }
}
