    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgBusquedaProducto.java
 *
 * Created on 08/07/2011, 12:12:00 PM
 */

package view.almAlmacen;

import controller.almAlmacen.CCProducto;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.TableColumn;
import modelo.almAlmacen.entidad.CEProducto;
import table.ArrayListTableModel;
import util.clases.grlGeneral.DialogoPadre;


public class DlgBusquedaNombreProducto extends DialogoPadre
{
  private  CEProducto oCEProducto;
   public DlgBusquedaNombreProducto(java.awt.Frame parent, boolean modal)
   {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        armarModelo();
        TxtProducto.requestFocus();


    }
    public void setCajaTexto(String TxtProducto)
    {
        if(TxtProducto!=null){
        this.TxtProducto.setText(TxtProducto);
        if(!this.TxtProducto.getText().equals("")){
            List<CEProducto> listaProducto=CCProducto.consultarProducto(this.TxtProducto.getText());
            AgregarProducto(listaProducto);}
        }
    }

     private void armarModelo()
    {
          
      TableColumn oColPr = TblProducto.getColumnModel().getColumn(0);
      oColPr.setPreferredWidth(15);
      oColPr = TblProducto.getColumnModel().getColumn(1);
      oColPr.setPreferredWidth(380);
      oColPr = TblProducto.getColumnModel().getColumn(2);
      oColPr.setPreferredWidth(90);




    }
     private void AgregarProducto(List<CEProducto> oLitaProducto)
    {        
        if(oLitaProducto!=null)
        {
            int i=0;
                for (CEProducto oCEProducto : oLitaProducto)
                {
                        ArrayList oArrayList=new ArrayList();
                        oArrayList.add(""+(i+1));
                        oArrayList.add(oCEProducto);
                        oArrayList.add(oCEProducto.getCodigo());
                        
                        ((ArrayListTableModel)TblProducto.getModel()).addRow(oArrayList);
                        i++;
                }
                LblItem.setText(""+i);

      }
    }


   

 



      private void limpiarTabla()
    {
         int size =TblProducto.getRowCount();
           for(int i=0;i<size;i++)
           {
                 ((ArrayListTableModel)TblProducto.getModel()).removeRow(0);
           }
    }
      

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblItem = new Label.Label();
        TxtProducto = new TextField.JTxtNinguno();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProducto = new javax.swing.JTable();
        label5 = new Label.Label();
        label6 = new Label.Label();
        btnCancelar1 = new BotonesABM.BtnCancelar();
        btnAceptar1 = new BotonesABM.BtnAceptar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda Producto");

        jPanel1.setBackground(new java.awt.Color(254, 254, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        LblItem.setText("0");
        LblItem.setFont(new java.awt.Font("Verdana", 1, 12));

        TxtProducto.setTamanio(200);
        TxtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtProductoKeyReleased(evt);
            }
        });

        TblProducto.setFont(new java.awt.Font("Verdana", 0, 11));
        TblProducto.setModel(new ArrayListTableModel(
            new Object [][] {

            },
            new String [] {"Nº","Producto",
                "Codigo"
            }
        ){
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.Object.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblProducto.setRowHeight(20);
        TblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblProductoMouseClicked(evt);
            }
        });
        TblProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TblProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblProductoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TblProducto);

        label5.setText("Nombre :");
        label5.setFont(new java.awt.Font("Verdana", 1, 12));

        label6.setText("Productos Encontrados :");
        label6.setFont(new java.awt.Font("Verdana", 1, 12));

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(LblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(595, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void TxtProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductoKeyReleased

        
        if(TblProducto.getRowCount()>0){
        if(evt.getKeyCode()==evt.VK_DOWN) {
            int size =TblProducto.getRowCount();
            if(size>0) {
                TblProducto.requestFocus();
                TblProducto.setRowSelectionInterval(0,0);
            }
        }
        }
      if(evt.getKeyCode()==evt.VK_ENTER) {
          limpiarTabla();
          if(!TxtProducto.getText().equals("")){
                List<CEProducto> listaProducto=CCProducto.consultarProducto(TxtProducto.getText());
                AgregarProducto(listaProducto);
          }
        }

    }//GEN-LAST:event_TxtProductoKeyReleased

    private void TblProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblProductoKeyPressed

           if(TblProducto.getRowCount()>0){
       TblProducto.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"ProjSave");
        TblProducto.getActionMap().put("ProjSave", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                eventoSelec();
            }
        });


        }
     
    }//GEN-LAST:event_TblProductoKeyPressed

   

    
   
   
    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed

        eventoSelec();
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void TblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblProductoMouseClicked

       
        
        if(evt.getClickCount()==2){
              eventoSelec();
                }

       
    }//GEN-LAST:event_TblProductoMouseClicked


    private void TblProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblProductoKeyReleased

    
        if(evt.getKeyCode()==evt.VK_UP) {
           // buscarCliente();
            int row=TblProducto.getSelectedRow();

               if(row!=-1)
               {
                   if(row==0)
                   {
                      // TxtProducto.requestFocus();
                      // LimpiarDetalle();
                   }
               }

        }

    }//GEN-LAST:event_TblProductoKeyReleased


    private void eventoSelec()
    {
        if(TblProducto.getSelectedRow()!=-1){

         oCEProducto=(CEProducto)TblProducto.getValueAt(TblProducto.getSelectedRow(), 1);
         dispose();
        }
}
    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
      dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

  public CEProducto getProductoAlmacen()
    {
      return oCEProducto;
  }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Label.Label LblItem;
    private javax.swing.JTable TblProducto;
    private TextField.JTxtNinguno TxtProducto;
    private BotonesABM.BtnAceptar btnAceptar1;
    private BotonesABM.BtnCancelar btnCancelar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Label.Label label5;
    private Label.Label label6;
    // End of variables declaration//GEN-END:variables
   
}
