/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgMantenimientoStockProducto.java
 *
 * Created on 23-dic-2011, 15:06:45
 */

package view.almAlmacen;

import controller.almAlmacen.CCAlmacenProducto;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.almAlmacen.entidad.CEAlmacenProducto;
import util.clases.grlGeneral.DialogoPadre;

/**
 *
 * @author Morales
 */
public class DlgMantenimientoStockProducto extends DialogoPadre {

    CEAlmacenProducto oCEAlmacenProducto=null;
    /** Creates new form DlgMantenimientoStockProducto */
    public DlgMantenimientoStockProducto(java.awt.Frame parent, boolean modal,CEAlmacenProducto oCEAlmacenProducto) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.oCEAlmacenProducto=oCEAlmacenProducto;
        cargarFormulario();
    }

    private void cargarFormulario()
    {
        LblAlmacen.setText(oCEAlmacenProducto.getAlmacen());
        LblSucursal.setText(oCEAlmacenProducto.getSucursal());
        LblProducto.setText(oCEAlmacenProducto.getDescripcion());
        LblUMB.setText(oCEAlmacenProducto.getUMB());
        LblStockReal.setText(""+oCEAlmacenProducto.getStockReal());
        TxtStockMinimo.setText(""+oCEAlmacenProducto.getStockMinimo());
        txtStockMax.setText(""+oCEAlmacenProducto.getStockMaximo());
        LblCostoUnit.setText(""+oCEAlmacenProducto.getCostoUnitario());
        LblInventario.setText(""+oCEAlmacenProducto.getInventario());
        TxtCostoCompra.setText(""+oCEAlmacenProducto.getUltimoCostocompra());


          List<CEAlmacenProducto> lista=CCAlmacenProducto.listarStockPorUnidadPedido(oCEAlmacenProducto);

            int i=1;
            for (CEAlmacenProducto obCEAlmacenProducto : lista) {

                 Vector oVector = new Vector();
                 oVector.add(i);
                 oVector.add(obCEAlmacenProducto.getUnidad_medida());
                 oVector.add(obCEAlmacenProducto.getEquivalenciaUMB());
                 oVector.add(obCEAlmacenProducto.getStockReal());
                 oVector.add(obCEAlmacenProducto.getCostoUnitario());
                 oVector.add(obCEAlmacenProducto.getUltimoCostocompra());

                ((DefaultTableModel)tblUnidadPedido.getModel()).addRow(oVector);
                i++;
            }
            if(tblUnidadPedido.getRowCount()>0)
            {
                tblUnidadPedido.requestFocus();
                tblUnidadPedido.changeSelection(0, 0, false, false);
            }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new Label.Label();
        label2 = new Label.Label();
        LblProducto = new Label.Label();
        LblAlmacen = new Label.Label();
        LblSucursal = new Label.Label();
        label6 = new Label.Label();
        label7 = new Label.Label();
        LblUMB = new Label.Label();
        label9 = new Label.Label();
        label11 = new Label.Label();
        label13 = new Label.Label();
        txtStockMax = new javax.swing.JTextField();
        TxtStockMinimo = new javax.swing.JTextField();
        btnGuardar1 = new BotonesABM.BtnGuardar();
        btnCancelar1 = new BotonesABM.BtnCancelar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnidadPedido = new javax.swing.JTable();
        label10 = new Label.Label();
        label12 = new Label.Label();
        LblInventario = new Label.Label();
        LblStockReal = new javax.swing.JTextField();
        LblCostoUnit = new javax.swing.JTextField();
        label14 = new Label.Label();
        label15 = new Label.Label();
        TxtCostoCompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Stock");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(222, 222, 250));
        label1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label1.setText("Producto  ");
        label1.setFont(new java.awt.Font("Verdana", 1, 12));
        label1.setOpaque(true);
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        label2.setBackground(new java.awt.Color(222, 222, 250));
        label2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label2.setText("UMB ");
        label2.setFont(new java.awt.Font("Verdana", 1, 12));
        label2.setOpaque(true);
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        LblProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblProducto.setText("Producto ");
        getContentPane().add(LblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 20, 460, -1));

        LblAlmacen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblAlmacen.setText("Almacen");
        getContentPane().add(LblAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 160, -1));

        LblSucursal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblSucursal.setText("Sucursal");
        getContentPane().add(LblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 160, -1));

        label6.setBackground(new java.awt.Color(222, 222, 250));
        label6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label6.setText("Sucursal   ");
        label6.setFont(new java.awt.Font("Verdana", 1, 12));
        label6.setOpaque(true);
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        label7.setBackground(new java.awt.Color(222, 222, 250));
        label7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label7.setText("Almacen ");
        label7.setFont(new java.awt.Font("Verdana", 1, 12));
        label7.setOpaque(true);
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 80, -1));

        LblUMB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblUMB.setText("UMB");
        getContentPane().add(LblUMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        label9.setBackground(new java.awt.Color(222, 222, 250));
        label9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label9.setText("Stock Real ");
        label9.setFont(new java.awt.Font("Verdana", 1, 12));
        label9.setOpaque(true);
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, -1));

        label11.setBackground(new java.awt.Color(222, 222, 250));
        label11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label11.setText("Stock MIN ");
        label11.setFont(new java.awt.Font("Verdana", 1, 12));
        label11.setOpaque(true);
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        label13.setBackground(new java.awt.Color(222, 222, 250));
        label13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label13.setText("Stock MAX ");
        label13.setFont(new java.awt.Font("Verdana", 1, 12));
        label13.setOpaque(true);
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        txtStockMax.setFont(new java.awt.Font("Verdana", 0, 12));
        txtStockMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStockMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtStockMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMaxActionPerformed(evt);
            }
        });
        getContentPane().add(txtStockMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 160, -1));

        TxtStockMinimo.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtStockMinimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtStockMinimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtStockMinimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtStockMinimoFocusGained(evt);
            }
        });
        getContentPane().add(TxtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, -1));

        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 333, -1, -1));

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 333, -1, -1));

        tblUnidadPedido.setFont(new java.awt.Font("Verdana", 0, 12));
        tblUnidadPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Unidad Media", "Equiv. uni.", "Stock", "Costo Unitario", "Costo Compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUnidadPedido.setRowHeight(22);
        jScrollPane1.setViewportView(tblUnidadPedido);
        tblUnidadPedido.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblUnidadPedido.getColumnModel().getColumn(1).setPreferredWidth(60);
        tblUnidadPedido.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblUnidadPedido.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblUnidadPedido.getColumnModel().getColumn(4).setPreferredWidth(90);
        tblUnidadPedido.getColumnModel().getColumn(5).setPreferredWidth(90);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 606, 121));

        label10.setBackground(new java.awt.Color(222, 222, 250));
        label10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label10.setText("Costo Uni ");
        label10.setFont(new java.awt.Font("Verdana", 1, 12));
        label10.setOpaque(true);
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        label12.setBackground(new java.awt.Color(222, 222, 250));
        label12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label12.setText("Inventario ");
        label12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label12.setOpaque(true);
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, -1));

        LblInventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblInventario.setText("0");
        getContentPane().add(LblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 160, -1));

        LblStockReal.setEditable(false);
        LblStockReal.setFont(new java.awt.Font("Verdana", 0, 12));
        LblStockReal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LblStockReal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblStockReal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LblStockRealFocusGained(evt);
            }
        });
        getContentPane().add(LblStockReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 160, -1));

        LblCostoUnit.setEditable(false);
        LblCostoUnit.setFont(new java.awt.Font("Verdana", 0, 12));
        LblCostoUnit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LblCostoUnit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblCostoUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LblCostoUnitFocusGained(evt);
            }
        });
        getContentPane().add(LblCostoUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, -1));

        label14.setText("Otras Unidades :");
        label14.setFont(new java.awt.Font("Verdana", 1, 12));
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        label15.setBackground(new java.awt.Color(222, 222, 250));
        label15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        label15.setText("Utmo. Costo Comp. ");
        label15.setFont(new java.awt.Font("Verdana", 1, 12));
        label15.setOpaque(true);
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        TxtCostoCompra.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtCostoCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtCostoCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtCostoCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCostoCompraFocusGained(evt);
            }
        });
        getContentPane().add(TxtCostoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        dispose();
}//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed

        oCEAlmacenProducto.setStockMaximo(Float.parseFloat(txtStockMax.getText()));
        oCEAlmacenProducto.setStockMinimo(Float.parseFloat(TxtStockMinimo.getText()));
        oCEAlmacenProducto.setStockReal(Float.parseFloat(LblStockReal.getText()));
        oCEAlmacenProducto.setCostoUnitario(Float.parseFloat(LblCostoUnit.getText()));
        oCEAlmacenProducto.setUltimoCostocompra(Float.parseFloat(TxtCostoCompra.getText()));
        boolean correcto=CCAlmacenProducto.UPDAlmacenProducto(oCEAlmacenProducto);
        if(correcto)
        {
            JOptionPane.showMessageDialog(null, "Operación Exitosa");
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Operación Fallida");
        }
        
}//GEN-LAST:event_btnGuardar1ActionPerformed

    private void TxtStockMinimoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtStockMinimoFocusGained
       TxtStockMinimo.selectAll();
    }//GEN-LAST:event_TxtStockMinimoFocusGained

    private void txtStockMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMaxActionPerformed
       txtStockMax.selectAll();
    }//GEN-LAST:event_txtStockMaxActionPerformed

    private void LblStockRealFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LblStockRealFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LblStockRealFocusGained

    private void LblCostoUnitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LblCostoUnitFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LblCostoUnitFocusGained

    private void TxtCostoCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCostoCompraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCostoCompraFocusGained

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Label.Label LblAlmacen;
    private javax.swing.JTextField LblCostoUnit;
    private Label.Label LblInventario;
    private Label.Label LblProducto;
    private javax.swing.JTextField LblStockReal;
    private Label.Label LblSucursal;
    private Label.Label LblUMB;
    private javax.swing.JTextField TxtCostoCompra;
    private javax.swing.JTextField TxtStockMinimo;
    private BotonesABM.BtnCancelar btnCancelar1;
    private BotonesABM.BtnGuardar btnGuardar1;
    private javax.swing.JScrollPane jScrollPane1;
    private Label.Label label1;
    private Label.Label label10;
    private Label.Label label11;
    private Label.Label label12;
    private Label.Label label13;
    private Label.Label label14;
    private Label.Label label15;
    private Label.Label label2;
    private Label.Label label6;
    private Label.Label label7;
    private Label.Label label9;
    private javax.swing.JTable tblUnidadPedido;
    private javax.swing.JTextField txtStockMax;
    // End of variables declaration//GEN-END:variables

}
