/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgMantenimientoSubfamiliao.java
 *
 * Created on 17/07/2011, 04:31:21 PM
 */

package view.almAlmacen;


import controller.almAlmacen.CCSubFamilia;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import modelo.almAlmacen.entidad.CESubfamilia;
import modelo.almAlmacen.entidad.CEFamilia;
import util.clases.grlGeneral.CLValidarControles;
import util.clases.grlGeneral.DialogoPadre;

/**
 *
 * @author Katya
 */
public class DlgMantenimientosubFamilia extends DialogoPadre implements ActionListener{

    private int opcionABM=1; //1= Guardar ,2 =Actuañlizar
private CESubfamilia oCESubfamilia;
private CEFamilia oCEFamilia;
    private CLValidarControles ovalidar;
    /** Creates new form DlgMantenimientoSubfamiliao */
    public DlgMantenimientosubFamilia(java.awt.Frame parent, boolean modal,CEFamilia oCEFamilia,String descCategoria,String descRubro)//nuevo
    {
        super(parent, modal);
        initComponents();

        this.oCEFamilia=oCEFamilia;
        TxtRubro.setText(descRubro);
        TxtCategoria.setText(descCategoria);
        TxtFamilia.setText(oCEFamilia.getDescripcion());
        TxtDescripcion.requestFocus();
         this.setLocationRelativeTo(null);
        this.opcionABM=1;
        CargarUtilidades();
    }
    public DlgMantenimientosubFamilia(java.awt.Frame parent, boolean modal,CESubfamilia oCESubfamilia,String dscFamilia,String descCategoria,String descRubro)//actualiar
    {
        super(parent, modal);
        initComponents();
        this.oCESubfamilia=oCESubfamilia;
        TxtCategoria.setText(descCategoria);
        TxtRubro.setText(descRubro);
        TxtFamilia.setText(dscFamilia);
        TxtCodigo.setText(oCESubfamilia.getCodigo());
        TxtDescripcion.setText(oCESubfamilia.getDescripcion());
        TxtCodigo.requestFocus();
        this.setLocationRelativeTo(null);
        this.opcionABM=2;
        CargarUtilidades();
    }
    private void CargarUtilidades()
    {
        ovalidar=new CLValidarControles();
      ovalidar.SetListCompnente(new Component[]{ TxtDescripcion},PnlFormulario);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFormulario = new javax.swing.JPanel();
        TxtCodigo = new TextField.JTxtNumero();
        TxtDescripcion = new TextField.JTxtLetra();
        label1 = new Label.Label();
        label2 = new Label.Label();
        TxtCategoria = new TextField.JTxtLetra();
        label3 = new Label.Label();
        label4 = new Label.Label();
        TxtRubro = new TextField.JTxtLetra();
        label5 = new Label.Label();
        TxtFamilia = new TextField.JTxtLetra();
        btnGuardar1 = new BotonesABM.BtnGuardar();
        btnCancelar1 = new BotonesABM.BtnCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro SubFamilia");

        PnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        TxtCodigo.setEditable(false);
        TxtCodigo.setTamanio(11);
        TxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyPressed(evt);
            }
        });

        TxtDescripcion.setTamanio(50);
        TxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDescripcionKeyPressed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(153, 0, 0));
        label1.setText("Codigo :");
        label1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        label2.setForeground(new java.awt.Color(153, 0, 0));
        label2.setText("Descripcion :");
        label2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TxtCategoria.setEditable(false);
        TxtCategoria.setTamanio(50);
        TxtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCategoriaKeyPressed(evt);
            }
        });

        label3.setForeground(new java.awt.Color(153, 0, 0));
        label3.setText("Categoria :");
        label3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        label4.setForeground(new java.awt.Color(153, 0, 0));
        label4.setText("Rubro :");
        label4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TxtRubro.setEditable(false);
        TxtRubro.setTamanio(50);
        TxtRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRubroKeyPressed(evt);
            }
        });

        label5.setForeground(new java.awt.Color(153, 0, 0));
        label5.setText("Familia :");
        label5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        TxtFamilia.setEditable(false);
        TxtFamilia.setTamanio(50);

        javax.swing.GroupLayout PnlFormularioLayout = new javax.swing.GroupLayout(PnlFormulario);
        PnlFormulario.setLayout(PnlFormularioLayout);
        PnlFormularioLayout.setHorizontalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtRubro, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(TxtCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                    .addGroup(PnlFormularioLayout.createSequentialGroup()
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        PnlFormularioLayout.setVerticalGroup(
            PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        btnGuardar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardar1KeyPressed(evt);
            }
        });

        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(PnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
dispose();
}//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed

        guardar();

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void guardar()

    {
        ovalidar.validarContorles();
        if(ovalidar.getisVacio()){

            int resul=JOptionPane.showConfirmDialog(this, "¿Esta seguro de Guardar? ", "Dialogo de Confirmación", JOptionPane.YES_NO_OPTION);
                if (resul==JOptionPane.YES_OPTION) {
                    CESubfamilia oCESubfamiliaTmp=new CESubfamilia();
                    oCESubfamiliaTmp.setDescripcion(TxtDescripcion.getText());

                    if(opcionABM==1){

                        oCESubfamiliaTmp.setIdFamilia(oCEFamilia.getIdFamilia());
                        oCESubfamiliaTmp.setCodigo(oCEFamilia.getCodigo()+TxtCodigo.getText());

                    }else{oCESubfamiliaTmp.setIdSubFamilia(this.oCESubfamilia.getIdSubFamilia());}


                        if(CCSubFamilia.ABMSubFamilia(opcionABM, oCESubfamiliaTmp)==1){
                       // JOptionPane.showMessageDialog(null,"se Guardo Con exito");
                            dispose();
                        }else{
                        JOptionPane.showMessageDialog(null, "Operación Fallida");
                        }
            }

            } else{
            TxtCodigo.requestFocus();
            JOptionPane.showMessageDialog(null,"Verificar Datos");

            }



    }
    private void TxtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            TxtDescripcion.requestFocus();
        }

    }//GEN-LAST:event_TxtCodigoKeyPressed

    private void TxtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescripcionKeyPressed
        if(evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_ENTER) {
            btnGuardar1.requestFocus();
        }
        if(evt.getKeyCode()==evt.VK_UP) {
            TxtCodigo.requestFocus();
        }
    }//GEN-LAST:event_TxtDescripcionKeyPressed

    private void btnGuardar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardar1KeyPressed
       if(evt.getKeyCode()==evt.VK_UP||evt.getKeyCode()==evt.VK_LEFT||evt.getKeyCode()==evt.VK_DOWN||evt.getKeyCode()==evt.VK_RIGHT) {
          TxtDescripcion.requestFocus();
      }
       if(evt.getKeyCode()==evt.VK_ENTER) {
          guardar();
      }
    }//GEN-LAST:event_btnGuardar1KeyPressed

    private void TxtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCategoriaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCategoriaKeyPressed

    private void TxtRubroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRubroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRubroKeyPressed

    
    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFormulario;
    private TextField.JTxtLetra TxtCategoria;
    private TextField.JTxtNumero TxtCodigo;
    private TextField.JTxtLetra TxtDescripcion;
    private TextField.JTxtLetra TxtFamilia;
    private TextField.JTxtLetra TxtRubro;
    private BotonesABM.BtnCancelar btnCancelar1;
    private BotonesABM.BtnGuardar btnGuardar1;
    private Label.Label label1;
    private Label.Label label2;
    private Label.Label label3;
    private Label.Label label4;
    private Label.Label label5;
    // End of variables declaration//GEN-END:variables

    private static final String ACTION_CLOSE = "ACTION_CLOSE";

    protected JRootPane createRootPane()
    {
        JRootPane rootPane = new JRootPane();

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        rootPane.registerKeyboardAction(this,ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
        return rootPane;
    }
    public void actionPerformed(ActionEvent e)
    {
    dispose();
    }

}
