/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgStockProducto.java
 *
 * Created on 08-dic-2011, 17:25:11
 */

package view.almAlmacen;

import controller.almAlmacen.CCAlmacen;
import controller.almAlmacen.CCAlmacenProducto;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.TableColumn;
import modelo.almAlmacen.entidad.CEAlmacen;
import modelo.almAlmacen.entidad.CEAlmacenProducto;
import net.sf.jasperreports.view.JasperViewer;
import table.ArrayListTableModel;
import util.clases.grlGeneral.CLBotonesABM;
import util.clases.grlGeneral.CLComboBox;
import util.clases.grlGeneral.CLExportarExcel;
import util.clases.grlGeneral.DialogoPadre;
import util.clases.reportes.CLReporte;
import util.clases.reportes.ClaseGestionDeReporte;
import util.clases.reportes.ClaseReporte;
import util.clases.reportes.ClaseReporte_Parametro;
import view.cmrComercial.DlgGestionProveedor;

/**
 *
 * @author Morales
 */
public class DlgStockProducto extends DialogoPadre {

    /** Creates new form DlgStockProducto */
    ArrayList<CEAlmacenProducto> listCEAlmacenProducto=null;
    java.awt.Frame parent;
    public DlgStockProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.parent=parent;
        CLBotonesABM oclBotonesABM= new CLBotonesABM();
        oclBotonesABM.setBotones(null, null, null, null, null, null,this);
        btnFinalizarPeriodo.setEnabled(false);
        configurarTabla();
        CbxAlmacen.setModel(CLComboBox.cargarCombo(CCAlmacen.listarAlmacenSucursal()));
        filtrarProducto();       
    }

    private void AgregarProducto(List<CEAlmacenProducto> oCEAlmacenProducto)
    {
        limpiarTabla();
        if(oCEAlmacenProducto!=null)
        {
            int i=0;
                for (CEAlmacenProducto CEAlmacenProducto : oCEAlmacenProducto)
                {
                        ArrayList oArrayList=new ArrayList();
                        oArrayList.add(""+(i+1));
                        oArrayList.add(CEAlmacenProducto);
                        oArrayList.add(CEAlmacenProducto.getCodigo());
                        oArrayList.add(CEAlmacenProducto.getUMB());
                        oArrayList.add(CEAlmacenProducto.getStockReal());
                        oArrayList.add(CEAlmacenProducto.getStockMinimo());
                        oArrayList.add(CEAlmacenProducto.getStockMaximo());                        
                        oArrayList.add(CEAlmacenProducto.getCostoUnitario());
                        oArrayList.add(CEAlmacenProducto.getInventario());
                        oArrayList.add(CEAlmacenProducto.getUltimoCostocompra());
                        oArrayList.add(CEAlmacenProducto.getAlmacen());
                        ((ArrayListTableModel)TblProducto.getModel()).addRow(oArrayList);
                        i++;
                }
                LblItem.setText(""+i);
      }
    }

    private void filtrarProducto()
    {
        CEAlmacen oCEAlmacen= (CEAlmacen)CbxAlmacen.getSelectedItem();
        if(oCEAlmacen!=null)
        {
            
            if(RbnUnidadBase.isSelected())
            listCEAlmacenProducto=CCAlmacenProducto.listarAlmacen(1,TxtProducto.getText(), oCEAlmacen.getIdAlmacen());
            else if (RbnTodos.isSelected())
            listCEAlmacenProducto=CCAlmacenProducto.listarAlmacen(8,TxtProducto.getText(), oCEAlmacen.getIdAlmacen());

            AgregarProducto(listCEAlmacenProducto);
        }
    }
    private void limpiarTabla()
    {
         int size =TblProducto.getRowCount();
           for(int i=0;i<size;i++)
           {
                 ((ArrayListTableModel)TblProducto.getModel()).removeRow(0);
           }
    }
    private void configurarTabla()
    {

      TableColumn oColPr = TblProducto.getColumnModel().getColumn(0);
      oColPr.setPreferredWidth(30);
      oColPr = TblProducto.getColumnModel().getColumn(1);
      oColPr.setPreferredWidth(380);
      oColPr = TblProducto.getColumnModel().getColumn(2);
      oColPr.setPreferredWidth(110);
      oColPr = TblProducto.getColumnModel().getColumn(3);
      oColPr.setPreferredWidth(90);
      oColPr = TblProducto.getColumnModel().getColumn(9);
      oColPr.setPreferredWidth(90);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProducto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnFiltrar = new javax.swing.JButton();
        CbxAlmacen = new ComboBox.ComboBox();
        label2 = new Label.Label();
        TxtProducto = new TextField.JTxtNinguno();
        label1 = new Label.Label();
        RbnUnidadBase = new javax.swing.JRadioButton();
        RbnTodos = new javax.swing.JRadioButton();
        btnEditar1 = new BotonesABM.BtnEditar();
        btnCancelar1 = new BotonesABM.BtnCancelar();
        LblItem = new Label.Label();
        label3 = new Label.Label();
        btnFinalizarPeriodo = new BotonesABM.BtnGuardar();
        btnExportar2 = new BotonesABM.BtnExportar();
        btnExportar1 = new BotonesABM.BtnExportar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock de Productos");

        TblProducto.setFont(new java.awt.Font("Verdana", 0, 11));
        TblProducto.setModel(new ArrayListTableModel(
            new Object [][] {

            },
            new String [] {"Nº","Producto",
                "Codigo","Unidad Medida","StockReal","StockMin",
                "StockMax","Costo Uni.",
                "Inventario","Costo Comp.","Almacen"
            }
        ){
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.Object.class,
                java.lang.String.class,java.lang.String.class,
                java.lang.String.class,java.lang.String.class,
                java.lang.String.class,java.lang.String.class,
                java.lang.String.class,java.lang.String.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false,false,false,false,false,
                false,false,false,false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblProducto.setRowHeight(22);
        TblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblProductoMouseClicked(evt);
            }
        });
        TblProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TblProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TblProductoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TblProducto);

        jPanel1.setBackground(new java.awt.Color(254, 254, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda Stock Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        BtnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/icono/Buscar.png"))); // NOI18N
        BtnFiltrar.setToolTipText("Filtrar Productos");
        BtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrarActionPerformed(evt);
            }
        });

        CbxAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxAlmacenActionPerformed(evt);
            }
        });

        label2.setText("Almacen - Sucursal :");

        TxtProducto.setText("jTxtNinguno1");
        TxtProducto.setTamanio(150);
        TxtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtProductoKeyReleased(evt);
            }
        });

        label1.setText("Producto :");

        buttonGroup1.add(RbnUnidadBase);
        RbnUnidadBase.setFont(new java.awt.Font("Verdana", 1, 11));
        RbnUnidadBase.setSelected(true);
        RbnUnidadBase.setText("Unidad Base");
        RbnUnidadBase.setOpaque(false);
        RbnUnidadBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbnUnidadBaseActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbnTodos);
        RbnTodos.setFont(new java.awt.Font("Verdana", 1, 11));
        RbnTodos.setText("Todas las Unidades");
        RbnTodos.setOpaque(false);
        RbnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbnTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbnUnidadBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbnTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbxAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(BtnFiltrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CbxAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(RbnUnidadBase)
                .addComponent(RbnTodos))
            .addComponent(BtnFiltrar)
        );

        BtnFiltrar.getAccessibleContext().setAccessibleName("0");

        btnEditar1.setToolTipText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        LblItem.setText("0");

        label3.setText("Registros Encontrados");

        btnFinalizarPeriodo.setIcon(null);
        btnFinalizarPeriodo.setText("<html>Finalizar<br>Periodo<html/>");
        btnFinalizarPeriodo.setToolTipText("Finalizar Perido");
        btnFinalizarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPeriodoActionPerformed(evt);
            }
        });

        btnExportar2.setText("Reportar");
        btnExportar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportar2ActionPerformed(evt);
            }
        });

        btnExportar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/icono/icono-excel.png"))); // NOI18N
        btnExportar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblItem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinalizarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnExportar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFinalizarPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblProductoMouseClicked


    }//GEN-LAST:event_TblProductoMouseClicked

    private void TblProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblProductoKeyPressed

        TblProducto.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"ProjSave");
        TblProducto.getActionMap().put("ProjSave", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {

                SeleccionarRegistro();


            }
        });

    }//GEN-LAST:event_TblProductoKeyPressed

    private void TblProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TblProductoKeyReleased


    }//GEN-LAST:event_TblProductoKeyReleased

    private void BtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarActionPerformed
filtrarProducto();
}//GEN-LAST:event_BtnFiltrarActionPerformed

    private void CbxAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxAlmacenActionPerformed
        filtrarProducto();
    }//GEN-LAST:event_CbxAlmacenActionPerformed

    private void TxtProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductoKeyPressed
       if(evt.getKeyCode()==evt.VK_ENTER)
        {
           filtrarProducto();
       }
    }//GEN-LAST:event_TxtProductoKeyPressed

    private void btnFinalizarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPeriodoActionPerformed

        
        boolean rpta=false;//CCAlmacenProducto.FinalizarPeriodo("");
        if(rpta)
        {
            JOptionPane.showMessageDialog(null,"Se finalizo el periodo con éxito");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Operación Fallida");
        }

    }//GEN-LAST:event_btnFinalizarPeriodoActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        SeleccionarRegistro();
    }//GEN-LAST:event_btnEditar1ActionPerformed


    private void SeleccionarRegistro()
    {
        if(TblProducto.getSelectedRow()!=-1)
      {
          CEAlmacenProducto oCEAlmacenProducto=(CEAlmacenProducto)TblProducto.getValueAt(TblProducto.getSelectedRow(), 1);
          if(CbxAlmacen.getSelectedIndex()!=-1)
          {
              CEAlmacen oCEAlmacen=(CEAlmacen)CbxAlmacen.getSelectedItem();
              oCEAlmacenProducto.setAlmacen(oCEAlmacen.getDescripcion());
              oCEAlmacenProducto.setSucursal(oCEAlmacen.getSucursal());
          }
          DlgMantenimientoStockProducto oventana=new DlgMantenimientoStockProducto(parent, true,oCEAlmacenProducto);
          oventana.setVisible(true);

         filtrarProducto();
      }
    }
    private void TxtProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProductoKeyReleased

        if(evt.getKeyCode()==evt.VK_DOWN) {
            if(TblProducto.getRowCount()>0)
        {
          TblProducto.requestFocus();
          TblProducto.changeSelection(0, 0, false, false);
        }
        }
    }//GEN-LAST:event_TxtProductoKeyReleased

    private void btnExportar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar2ActionPerformed

          ClaseReporte oClaseReporte = new ClaseReporte();
        String oUrlC = null;
        CLReporte oCLReporte = new CLReporte();
        String UrlReporte="";

        UrlReporte="/view/almAlmacen/rptALMReportes/ALMRPTStockAlmacen.jasper";        

        URL oUrlRC = getClass().getResource(UrlReporte);
        oCLReporte.setUrlReport(oUrlRC.toString());
        oUrlC = oCLReporte.getUrlReport().replace('\'', '/');
        if (oCLReporte != null)
        {
            oClaseReporte.setUrl(oUrlC);
            ClaseGestionDeReporte oGestionDeReporte = new ClaseGestionDeReporte();

            CEAlmacen oCEAlmacen=(CEAlmacen)CbxAlmacen.getSelectedItem();
            ClaseReporte_Parametro oClaseParametroconcepto = new ClaseReporte_Parametro();
            oClaseParametroconcepto.setNombre("pidalmacen");
            oClaseParametroconcepto.setPParametro(""+oCEAlmacen.getIdAlmacen());


            Vector<ClaseReporte_Parametro> oLstParametro = new Vector<ClaseReporte_Parametro>();
            oLstParametro.add(oClaseParametroconcepto);

            oClaseReporte.setoLstParametros(oLstParametro);

            JasperViewer jviewer = new JasperViewer(oGestionDeReporte.ejecutarReporte(oClaseReporte), false);
            jviewer.setTitle("Reporte");
            jviewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);

            jviewer.setVisible(true);

        }
        else
        {
            JOptionPane.showMessageDialog(null, "El reporte no se encuentra");
        }


    
    }//GEN-LAST:event_btnExportar2ActionPerformed

    private void btnExportar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportar1ActionPerformed

        CLExportarExcel oExportar=new CLExportarExcel(TblProducto,
                new String[]{},new String[]{},new String[]{}
        ,this.getTitle());
        oExportar.GuardarArchivoExcel(this);
}//GEN-LAST:event_btnExportar1ActionPerformed

    private void RbnUnidadBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbnUnidadBaseActionPerformed
        filtrarProducto();
    }//GEN-LAST:event_RbnUnidadBaseActionPerformed

    private void RbnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbnTodosActionPerformed
        filtrarProducto();
    }//GEN-LAST:event_RbnTodosActionPerformed

     private void buscarProveedor()
    {

//        if(ChkProv.isSelected()){
//
//                  DlgGestionProveedor odialogo= new DlgGestionProveedor(null, true,1,1,1);//consultar
//
//                  odialogo.setCajaTexo(TxtProveedor1.getText());
//                  odialogo.setVisible(true);
//                  odialogo.setTitle("Busqueda de Proveedor");
//                          if(odialogo.getoCEProveedor()!=null){
//                            idProveedor=odialogo.getoCEProveedor().getIdProveedor();
//                            TxtProveedor1.setText(odialogo.getoCEProveedor().getRazonSocial());
//                            BtnFiltrar.requestFocus();
//                            }
//        }
      }

    private int idProveedor=0;

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFiltrar;
    private ComboBox.ComboBox CbxAlmacen;
    private Label.Label LblItem;
    private javax.swing.JRadioButton RbnTodos;
    private javax.swing.JRadioButton RbnUnidadBase;
    private javax.swing.JTable TblProducto;
    private TextField.JTxtNinguno TxtProducto;
    private BotonesABM.BtnCancelar btnCancelar1;
    private BotonesABM.BtnEditar btnEditar1;
    private BotonesABM.BtnExportar btnExportar1;
    private BotonesABM.BtnExportar btnExportar2;
    private BotonesABM.BtnGuardar btnFinalizarPeriodo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Label.Label label1;
    private Label.Label label2;
    private Label.Label label3;
    // End of variables declaration//GEN-END:variables

}
