/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgAuditoriaComprobanteVenta.java
 *
 * Created on 06/10/2012, 03:15:16 PM
 */

package view.vtaVenta;

import controller.vtaVenta.CCComprobanteVenta;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelo.vtaVenta.entidad.CEComprobanteVentaMatriz;
import util.clases.grlGeneral.DialogoPadre;

/**
 *
 * @author Morales
 */
public class DlgAuditoriaComprobanteVenta extends DialogoPadre{

    /** Creates new form DlgAuditoriaComprobanteVenta */
    public DlgAuditoriaComprobanteVenta(java.awt.Frame parent, boolean modal,CEComprobanteVentaMatriz oCEComprobanteVentaMatriz) {
        super(parent, modal);
        initComponents();
        TxtCliente.setText(oCEComprobanteVentaMatriz.getCliente());
        TxtNum.setText(oCEComprobanteVentaMatriz.getNumComprobante());
        listarRegistros(oCEComprobanteVentaMatriz.getIdComprobanteVenta());
    }


    private void listarRegistros(long id)
    {
         
        List<CEComprobanteVentaMatriz> lista=CCComprobanteVenta.ConsultarAuditoria(id);
        int i=0;
        for (CEComprobanteVentaMatriz oCEComprobanteVentaMatriz : lista) {
             Vector oArrayList = new Vector();                                
                
           ((DefaultTableModel)TblComprobante.getModel()).addRow(oArrayList);
            TblComprobante.setValueAt(oCEComprobanteVentaMatriz.getUltimaFecha(),i,0);
            TblComprobante.setValueAt(oCEComprobanteVentaMatriz.getUltimoEstado(),i,1);
            TblComprobante.setValueAt(oCEComprobanteVentaMatriz.getUltimoUsuario(),i,2);
            TblComprobante.setValueAt(oCEComprobanteVentaMatriz.getUltimaObservacion(),i,3);
            i++;
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblComprobante = new javax.swing.JTable();
        lblCliente = new Label.Label();
        TxtCliente = new TextField.JTxtNinguno();
        lblCliente1 = new Label.Label();
        TxtNum = new TextField.JTxtNinguno();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Auditoria De comprobante");

        TblComprobante.setFont(new java.awt.Font("Tahoma", 0, 12));
        TblComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Estado", "Usuario", "Observacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblComprobante.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TblComprobante.setRowHeight(20);
        jScrollPane1.setViewportView(TblComprobante);
        TblComprobante.getColumnModel().getColumn(0).setPreferredWidth(140);
        TblComprobante.getColumnModel().getColumn(1).setPreferredWidth(125);
        TblComprobante.getColumnModel().getColumn(2).setPreferredWidth(135);
        TblComprobante.getColumnModel().getColumn(3).setPreferredWidth(415);

        lblCliente.setBackground(new java.awt.Color(204, 204, 255));
        lblCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCliente.setText("Cliente :");
        lblCliente.setOpaque(true);

        TxtCliente.setEditable(false);
        TxtCliente.setTamanio(250);
        TxtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClienteActionPerformed(evt);
            }
        });
        TxtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtClienteKeyReleased(evt);
            }
        });

        lblCliente1.setBackground(new java.awt.Color(204, 204, 255));
        lblCliente1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCliente1.setText("Numero :");
        lblCliente1.setOpaque(true);

        TxtNum.setEditable(false);
        TxtNum.setTamanio(250);
        TxtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumActionPerformed(evt);
            }
        });
        TxtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNumKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtClienteActionPerformed

    private void TxtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClienteKeyPressed

        
    }//GEN-LAST:event_TxtClienteKeyPressed

    private void TxtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClienteKeyReleased


       

    }//GEN-LAST:event_TxtClienteKeyReleased

    private void TxtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumActionPerformed

    private void TxtNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumKeyPressed

    private void TxtNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumKeyReleased

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblComprobante;
    private TextField.JTxtNinguno TxtCliente;
    private TextField.JTxtNinguno TxtNum;
    private javax.swing.JScrollPane jScrollPane1;
    private Label.Label lblCliente;
    private Label.Label lblCliente1;
    // End of variables declaration//GEN-END:variables

}
