/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgConsultarPrecio.java
 *
 * Created on 01/09/2011, 06:27:46 PM
 */

package view.vtaVenta;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import modelo.almAlmacen.entidad.CEProductoPrecio;
import util.clases.grlGeneral.DialogoPadre;
import util.clases.grlGeneral.VerificadorDeTxt;

/**
 *
 * @author Luiggi
 */
public class DlgConsultarPrecio extends DialogoPadre{

    /** Creates new form DlgConsultarPrecio */
    int accion=0;// accion=0 :Consultar ; accion=1 :IngersarPrecio accion=2 modificar
    float Precio=0;
    public DlgConsultarPrecio(java.awt.Frame parent, boolean modal,List<CEProductoPrecio> olistaPrecio,
                             String Producto,String Unidad,int accion,boolean isModificable,float Precio,
                              float cantidadActual) {
        super(parent, modal);
        initComponents();
        LblProducto.setText(Producto);
        LblUnidad.setText(Unidad);
        LblPrecio.setVisible(false);
        TxtPrecio.setVisible(false);
        TxtPrecio.setDocument(new VerificadorDeTxt("Numero",0,TxtPrecio));
        LblCantidad.setText(""+cantidadActual);
        this.accion=accion;
        for(CEProductoPrecio oCEProductoPrecioTemp : olistaPrecio)
          {

                  Vector oArrayList=new Vector();
                        oArrayList.add(""+oCEProductoPrecioTemp.getRangoInicial());
                        oArrayList.add(""+oCEProductoPrecioTemp.getRangoFinal());
                        oArrayList.add(""+oCEProductoPrecioTemp.getPrecioUnitario());
                        ((DefaultTableModel)TblPrecios.getModel()).addRow(oArrayList);

          }
        if(!isModificable){
            TxtPrecio.setEnabled(false);
            LblMensaje.setText("<html>la cantidad actual <BR>ya tiene un precio establecido</html>");
        }
        if(accion==1 ||accion==2)
        {
          TxtPrecio.setDocument(new VerificadorDeTxt("Numero",0,TxtPrecio));
          LblPrecio.setVisible(true);
          TxtPrecio.setVisible(true);
          LblMensaje.setVisible(false);
          TxtPrecio.setText("");
          if(accion==2){
              TxtPrecio.setText(""+Precio);
          }
        }
        if(accion==4) // solo lo pueden hacer los q tienen permisos
        {
          TxtPrecio.setDocument(new VerificadorDeTxt("Numero",0,TxtPrecio));
          LblPrecio.setVisible(true);
          TxtPrecio.setVisible(true);
          LblMensaje.setVisible(false);
          TxtPrecio.setText(""+Precio);
          TxtPrecio.setEnabled(true);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblProducto = new javax.swing.JLabel();
        LblUnidad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPrecios = new javax.swing.JTable();
        LblPrecio = new javax.swing.JLabel();
        btnAceptar1 = new BotonesABM.BtnAceptar();
        TxtPrecio = new javax.swing.JTextField();
        LblMensaje = new Label.Label();
        LblPrecio1 = new javax.swing.JLabel();
        LblCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel1.setText("Producto :");

        LblProducto.setFont(new java.awt.Font("Verdana", 1, 12));

        LblUnidad.setFont(new java.awt.Font("Verdana", 1, 12));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel4.setText("Unidad :");

        jPanel2.setBackground(new java.awt.Color(254, 254, 239));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Precios ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        TblPrecios.setFont(new java.awt.Font("Verdana", 0, 12));
        TblPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rango Inicial", "Rango Final", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblPrecios.setEnabled(false);
        TblPrecios.setRowHeight(22);
        jScrollPane2.setViewportView(TblPrecios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblPrecio.setFont(new java.awt.Font("Verdana", 1, 12));
        LblPrecio.setText("Precio :");

        btnAceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAceptar1.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        TxtPrecio.setFont(new java.awt.Font("Verdana", 0, 12));
        TxtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TxtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtPrecioFocusGained(evt);
            }
        });
        TxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyPressed(evt);
            }
        });

        LblMensaje.setForeground(new java.awt.Color(153, 0, 0));

        LblPrecio1.setFont(new java.awt.Font("Verdana", 1, 12));
        LblPrecio1.setText("Cantidad Actual :");

        LblCantidad.setFont(new java.awt.Font("Verdana", 1, 12));
        LblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCantidad.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(LblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(LblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblPrecio)
                        .addGap(67, 67, 67)
                        .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblPrecio1)
                        .addGap(6, 6, 6)
                        .addComponent(LblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(LblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(LblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblPrecio1)
                            .addComponent(LblCantidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(LblPrecio))
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed

        if(accion==1||accion==2||accion==4)
        {

            if(!TxtPrecio.getText().equals("")){
            Precio=Float.parseFloat(TxtPrecio.getText());}
            if(Precio<=0)
            {
                JOptionPane.showMessageDialog(null,"El Precio debe ser mayor a cero","Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                TxtPrecio.requestFocus();
            }else{dispose();}
        }else{
        dispose();}
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void TxtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyPressed
       if(evt.getKeyCode()==evt.VK_ENTER|| evt.getKeyCode()==evt.VK_DOWN) {
            btnAceptar1.requestFocus();

        }
    }//GEN-LAST:event_TxtPrecioKeyPressed

    private void TxtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtPrecioFocusGained
        TxtPrecio.selectAll();
    }//GEN-LAST:event_TxtPrecioFocusGained

    public float getPrecio() {
        return Precio;
    }

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCantidad;
    private Label.Label LblMensaje;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblPrecio1;
    private javax.swing.JLabel LblProducto;
    private javax.swing.JLabel LblUnidad;
    private javax.swing.JTable TblPrecios;
    private javax.swing.JTextField TxtPrecio;
    private BotonesABM.BtnAceptar btnAceptar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private static final String ACTION_CLOSE = "ACTION_CLOSE";

    protected JRootPane createRootPane()
    {
        JRootPane rootPane = new JRootPane();

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        rootPane.registerKeyboardAction(this,ACTION_CLOSE, esc, JComponent.WHEN_IN_FOCUSED_WINDOW);
   
        return rootPane;
    }
    public void actionPerformed(ActionEvent e)
    {
        if(e.getActionCommand().equals(ACTION_CLOSE))
        {
            dispose();
        }
    }

}
