/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPuntoVentaComprobante.java
 *
 * Created on 28-feb-2013, 23:40:20
 */

package view.vtaVenta;

import controller.vtaVenta.CCPuntoVenta;
import controller.vtaVenta.CCSerie;
import controller.vtaVenta.CCSucursal;
import controller.vtaVenta.CCTipoComprobante;
import java.awt.Component;
import javax.swing.JOptionPane;
import modelo.grlGeneral.entidad.CEImpresora;
import modelo.vtaVenta.entidad.CEPuntoVenta;
import modelo.vtaVenta.entidad.CESerie;
import modelo.vtaVenta.entidad.CESucursal;
import modelo.vtaVenta.entidad.CETipoComprobante;
import util.clases.grlGeneral.CLComboBox;
import util.clases.grlGeneral.CLValidarControles;
import util.clases.grlGeneral.CLValidarControlesDlg;
import util.clases.grlGeneral.VerificadorDeTxt;
import util.clases.vtaVenta.CLCargarCombo;

/**
 *
 * @author Morales
 */
public class DlgPuntoVentaComprobante extends javax.swing.JDialog {

    /** Creates new form DlgPuntoVentaComprobante */
    boolean vnuevoRegistro;
    CESerie oCESerie;
    private CLValidarControlesDlg ovalidar;
    public DlgPuntoVentaComprobante(java.awt.Frame parent, boolean modal,CESerie pCeSerie,boolean nuevoregistro) {
        super(parent, modal);
        initComponents();
        ovalidar= new CLValidarControlesDlg();
        ovalidar.SetListCompnente(new Component[]{TxtAlto,TxtAncho,TxtCerosCorrelativo,TxtCerosSerie,TxtCorrelativo,TxtNumeroSerie}, this);
        vnuevoRegistro=nuevoregistro;
        oCESerie=pCeSerie;
        CbxSucursal.setModel(CLComboBox.cargarCombo(CCSucursal.getAll()));
        int idSucursal=((CESucursal)CbxSucursal.getSelectedItem()).getIdSucursal();
        CbxPuntoVenta.setModel(CLComboBox.cargarCombo(CCPuntoVenta.listarPuntoVenta_Todo(idSucursal)));
        CEImpresora oCEImpresora = new CEImpresora();
        CbxImpresora.setModel(CLComboBox.cargarCombo(oCEImpresora.ListarImpresorasConNiguno()));
        CbxTipoComprobante.setModel(CLComboBox.cargarCombo(CCTipoComprobante.listarTodos()));
        TxtAlto.setDocument(new VerificadorDeTxt("Numero",7,TxtAlto));
        TxtAncho.setDocument(new VerificadorDeTxt("Numero",7,TxtAncho));
        if(!nuevoregistro)
        {
            setSerie();
        }
      GenerarNumeroComprobante();
    }
    private void setSerie()
    {
        CLCargarCombo.buscarIdTipoComprobante(CbxTipoComprobante,oCESerie.getIdTipoComprobante());
        CEImpresora oCEImpresora= new CEImpresora();
        CbxImpresora.setSelectedIndex(oCEImpresora.buscarIndiceImpresoraDesdeCbx(oCESerie.getNombreImpresora(),CbxImpresora));
        TxtAlto.setText(oCESerie.getAlto()+"");
        TxtAncho.setText(oCESerie.getAncho()+"");
        TxtCerosCorrelativo.setText(oCESerie.getCeroCorrelativo()+"");
        TxtCerosSerie.setText(""+oCESerie.getCeroSerie());
        TxtCorrelativo.setText(""+oCESerie.getUltimoNumeroGenerado());
        TxtNumeroSerie.setText(""+oCESerie.getNumero());
        CbxSucursal.setEnabled(false);
        CbxPuntoVenta.setEnabled(false);
        CbxTipoComprobante.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbxPuntoVenta = new ComboBox.ComboBox();
        label12 = new Label.Label();
        label13 = new Label.Label();
        label14 = new Label.Label();
        label15 = new Label.Label();
        CbxImpresora = new ComboBox.ComboBox();
        label16 = new Label.Label();
        CbxTipoComprobante = new ComboBox.ComboBox();
        label17 = new Label.Label();
        label18 = new Label.Label();
        TxtCorrelativo = new TextField.JTxtNumero();
        TxtCerosSerie = new TextField.JTxtNumero();
        TxtNumeroSerie = new TextField.JTxtNumero();
        TxtCerosCorrelativo = new TextField.JTxtNumero();
        label19 = new Label.Label();
        LblDemoNum = new Label.Label();
        label21 = new Label.Label();
        label22 = new Label.Label();
        TxtAlto = new javax.swing.JTextField();
        TxtAncho = new javax.swing.JTextField();
        btnGuardar = new BotonesABM.BtnGuardar();
        btnCancelar = new BotonesABM.BtnCancelar();
        jButton1 = new javax.swing.JButton();
        CbxSucursal = new ComboBox.ComboBox();
        label20 = new Label.Label();
        label23 = new Label.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Punto Venta - Serie - Comprobante");

        CbxPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxPuntoVentaActionPerformed(evt);
            }
        });

        label12.setText("Punto Venta    ");
        label12.setFont(new java.awt.Font("Verdana", 1, 12));

        label13.setText("Numero Serie            ");
        label13.setFont(new java.awt.Font("Verdana", 1, 12));

        label14.setText("Ultimo Correlativo     ");
        label14.setFont(new java.awt.Font("Verdana", 1, 12));

        label15.setText("Impresora   ");
        label15.setFont(new java.awt.Font("Verdana", 1, 12));

        CbxImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxImpresoraActionPerformed(evt);
            }
        });

        label16.setText("Tipo Comprobante    ");
        label16.setFont(new java.awt.Font("Verdana", 1, 12));

        CbxTipoComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxTipoComprobanteActionPerformed(evt);
            }
        });

        label17.setText("Nº Digitos");
        label17.setFont(new java.awt.Font("Verdana", 1, 12));

        label18.setText("Nº Digitos ");
        label18.setFont(new java.awt.Font("Verdana", 1, 12));

        TxtCorrelativo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtCorrelativo.setTamanio(8);
        TxtCorrelativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCorrelativoFocusGained(evt);
            }
        });
        TxtCorrelativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCorrelativoKeyReleased(evt);
            }
        });

        TxtCerosSerie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtCerosSerie.setText("jTxtNumero1");
        TxtCerosSerie.setTamanio(2);
        TxtCerosSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCerosSerieFocusGained(evt);
            }
        });
        TxtCerosSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCerosSerieKeyReleased(evt);
            }
        });

        TxtNumeroSerie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtNumeroSerie.setText("jTxtNumero1");
        TxtNumeroSerie.setTamanio(3);
        TxtNumeroSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtNumeroSerieFocusGained(evt);
            }
        });
        TxtNumeroSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNumeroSerieKeyReleased(evt);
            }
        });

        TxtCerosCorrelativo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtCerosCorrelativo.setText("jTxtNumero1");
        TxtCerosCorrelativo.setTamanio(2);
        TxtCerosCorrelativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtCerosCorrelativoFocusGained(evt);
            }
        });
        TxtCerosCorrelativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCerosCorrelativoKeyReleased(evt);
            }
        });

        label19.setText("Demo Nº Comprob.   ");
        label19.setFont(new java.awt.Font("Verdana", 1, 12));

        LblDemoNum.setBackground(new java.awt.Color(255, 255, 255));
        LblDemoNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LblDemoNum.setForeground(new java.awt.Color(204, 0, 0));
        LblDemoNum.setText("001-0034567");
        LblDemoNum.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LblDemoNum.setOpaque(true);

        label21.setText("Alto Comprobante");
        label21.setFont(new java.awt.Font("Verdana", 1, 12));

        label22.setText("Ancho Comprobante");
        label22.setFont(new java.awt.Font("Verdana", 1, 12));

        TxtAlto.setFont(new java.awt.Font("Verdana", 1, 11));
        TxtAlto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtAlto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtAltoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtAltoFocusLost(evt);
            }
        });
        TxtAlto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAltoKeyReleased(evt);
            }
        });

        TxtAncho.setFont(new java.awt.Font("Verdana", 1, 11));
        TxtAncho.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtAncho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtAncho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxtAnchoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtAnchoFocusLost(evt);
            }
        });
        TxtAncho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAnchoKeyReleased(evt);
            }
        });

        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CbxSucursal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxSucursalItemStateChanged(evt);
            }
        });
        CbxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSucursalActionPerformed(evt);
            }
        });

        label20.setText("Sucursal     ");
        label20.setFont(new java.awt.Font("Verdana", 1, 12));

        label23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label23.setText("NUEVO REGISTRO");
        label23.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CbxImpresora, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                        .addComponent(CbxTipoComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CbxSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                                                .addComponent(CbxPuntoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)))))
                                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtCorrelativo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtNumeroSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtCerosCorrelativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtCerosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label23, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                                    .addGap(16, 16, 16))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(label22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LblDemoNum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addGap(53, 53, 53)
                                    .addComponent(jButton1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(305, 305, 305))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtCerosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCerosCorrelativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDemoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxPuntoVentaActionPerformed
        
}//GEN-LAST:event_CbxPuntoVentaActionPerformed

    private void CbxImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxImpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxImpresoraActionPerformed

    private void CbxTipoComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxTipoComprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxTipoComprobanteActionPerformed

    private void TxtAltoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtAltoFocusGained
        TxtAlto.selectAll();
}//GEN-LAST:event_TxtAltoFocusGained

    private void TxtAltoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtAltoFocusLost
       
}//GEN-LAST:event_TxtAltoFocusLost

    private void TxtAltoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAltoKeyReleased
        
}//GEN-LAST:event_TxtAltoKeyReleased

    private void TxtAnchoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtAnchoFocusGained
        TxtAncho.selectAll();
    }//GEN-LAST:event_TxtAnchoFocusGained

    private void TxtAnchoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtAnchoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnchoFocusLost

    private void TxtAnchoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnchoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAnchoKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ovalidar.validarContorles();
        if(ovalidar.getisVacio()){
        ovalidar.ReiniciarCajas();
        
            CETipoComprobante oCETipoComprobante=(CETipoComprobante)CbxTipoComprobante.getSelectedItem();
            CEPuntoVenta oCEPuntoVenta=(CEPuntoVenta)CbxPuntoVenta.getSelectedItem();
                       
            this.getserie();
            boolean grabado=false;
            if(vnuevoRegistro)
            {
               int numeroRegistroExistente=CCSerie.consultaExistePuntoComprobante(oCETipoComprobante.getIdTipoComprobante(), oCEPuntoVenta.getIdPuntoVenta());
               if(numeroRegistroExistente==0){
                grabado=CCSerie.InsPuntoVentaComprobante(oCESerie);
                }
                 else
                    {
                     JOptionPane.showMessageDialog(this,"No se puede guardar por que\n "+"El Punto Venta : "+ oCEPuntoVenta.getDescrpcion()+" y"+
                                                       "\nEl tipo de Comprobante : "+oCETipoComprobante.getDescripcion() +"\nya exiten.");
                     return;
                    }
            }
            else
            {
               grabado=CCSerie.UPDPuntoVentaComprobante(oCESerie);
            }


            if(grabado)
            {
             JOptionPane.showMessageDialog(this,"Se Guardo con éxito");
            }else
            {
             JOptionPane.showMessageDialog(this,"Operación fallida");
            }
            dispose();
            

      }
}//GEN-LAST:event_btnGuardarActionPerformed

    private void getserie()
    {
        CETipoComprobante oCETipoComprobante=(CETipoComprobante)CbxTipoComprobante.getSelectedItem();
        CEPuntoVenta oCEPuntoVenta =(CEPuntoVenta)CbxPuntoVenta.getSelectedItem();
        int idSucursal=((CESucursal)CbxSucursal.getSelectedItem()).getIdSucursal();
        oCEPuntoVenta.setIdSucursal(idSucursal);
        oCESerie.setIdTipoComprobante(oCETipoComprobante.getIdTipoComprobante());
        oCESerie.setoCEPuntoVenta(oCEPuntoVenta);
        oCESerie.setNombreImpresora(CbxImpresora.getSelectedItem().toString());
        oCESerie.setNumero(TxtNumeroSerie.getText());
        oCESerie.setUltimoNumeroGenerado(VerificadorDeTxt.convertLong(TxtCorrelativo.getText()));
        oCESerie.setAlto(VerificadorDeTxt.convertFloat(TxtAlto.getText()));
        oCESerie.setAncho(VerificadorDeTxt.convertFloat(TxtAncho.getText()));
        oCESerie.setCeroCorrelativo(VerificadorDeTxt.convertInteger(TxtCerosCorrelativo.getText()));
        oCESerie.setCeroSerie(VerificadorDeTxt.convertInteger(TxtCerosSerie.getText()));
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();
        
}//GEN-LAST:event_btnCancelarActionPerformed

    private void TxtCorrelativoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorrelativoKeyReleased

        GenerarNumeroComprobante();
    }//GEN-LAST:event_TxtCorrelativoKeyReleased

    private void TxtNumeroSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroSerieKeyReleased
        GenerarNumeroComprobante();
    }//GEN-LAST:event_TxtNumeroSerieKeyReleased

    private void TxtCerosCorrelativoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCerosCorrelativoKeyReleased
        GenerarNumeroComprobante();
    }//GEN-LAST:event_TxtCerosCorrelativoKeyReleased

    private void TxtCerosSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCerosSerieKeyReleased
        GenerarNumeroComprobante();
    }//GEN-LAST:event_TxtCerosSerieKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GenerarNumeroComprobante();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbxSucursalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxSucursalItemStateChanged

}//GEN-LAST:event_CbxSucursalItemStateChanged

    private void CbxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSucursalActionPerformed

        int idSucursal=((CESucursal)CbxSucursal.getSelectedItem()).getIdSucursal();
        CbxPuntoVenta.setModel(CLComboBox.cargarCombo(CCPuntoVenta.listarPuntoVenta_Todo(idSucursal)));
    }//GEN-LAST:event_CbxSucursalActionPerformed

    private void TxtCorrelativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCorrelativoFocusGained
       TxtCorrelativo.selectAll();
    }//GEN-LAST:event_TxtCorrelativoFocusGained

    private void TxtCerosCorrelativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCerosCorrelativoFocusGained
        TxtCerosCorrelativo.selectAll();
    }//GEN-LAST:event_TxtCerosCorrelativoFocusGained

    private void TxtNumeroSerieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtNumeroSerieFocusGained
        TxtNumeroSerie.selectAll();
    }//GEN-LAST:event_TxtNumeroSerieFocusGained

    private void TxtCerosSerieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCerosSerieFocusGained
        TxtCerosSerie.selectAll();
    }//GEN-LAST:event_TxtCerosSerieFocusGained

    private void GenerarNumeroComprobante()
    {
        int CeroSerie=0;
        if(!TxtCerosSerie.getText().equals(""))
        {
           CeroSerie=Integer.parseInt(TxtCerosSerie.getText());
        }

        int CeroCorrelativo=0;
        if(!TxtCerosCorrelativo.getText().equals(""))
        {
           CeroCorrelativo=Integer.parseInt(TxtCerosCorrelativo.getText());
        }
        String NumSerie=TxtNumeroSerie.getText();
        String NumCorrelativo=TxtCorrelativo.getText();

        String serieGenerada=NumSerie;
        String CorrelativoGenerado=NumCorrelativo;
        for(int i=NumSerie.length();i<CeroSerie;i++)
        {
            serieGenerada="0"+serieGenerada;
        }
        for(int i=NumCorrelativo.length();i<CeroCorrelativo;i++)
        {
            CorrelativoGenerado="0"+CorrelativoGenerado;
        }

       LblDemoNum.setText(serieGenerada+"-"+CorrelativoGenerado);
    }
    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComboBox.ComboBox CbxImpresora;
    private ComboBox.ComboBox CbxPuntoVenta;
    private ComboBox.ComboBox CbxSucursal;
    private ComboBox.ComboBox CbxTipoComprobante;
    private Label.Label LblDemoNum;
    private javax.swing.JTextField TxtAlto;
    private javax.swing.JTextField TxtAncho;
    private TextField.JTxtNumero TxtCerosCorrelativo;
    private TextField.JTxtNumero TxtCerosSerie;
    private TextField.JTxtNumero TxtCorrelativo;
    private TextField.JTxtNumero TxtNumeroSerie;
    private BotonesABM.BtnCancelar btnCancelar;
    private BotonesABM.BtnGuardar btnGuardar;
    private javax.swing.JButton jButton1;
    private Label.Label label12;
    private Label.Label label13;
    private Label.Label label14;
    private Label.Label label15;
    private Label.Label label16;
    private Label.Label label17;
    private Label.Label label18;
    private Label.Label label19;
    private Label.Label label20;
    private Label.Label label21;
    private Label.Label label22;
    private Label.Label label23;
    // End of variables declaration//GEN-END:variables

}
